### ISSUE TITLE
CVRF V1.2 Schema Locations Broken

### ISSUE THREAD

**Issue by constcast** [oasis-tcs/csaf#10]
Hi, 

the schema files in the repository and on the OASIS web site cannot currently be used to validate CVRF V1.2 files. 

The namespace definition published at:

http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/cvrf 

refers to the schema location at:

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas

However, the cvrf.xsd in this GIT repository (cvrf_1.2/csaf_cvrf/schemas/cvrf.xsd), and on the OASIS website (http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/cvrf.xsd) reference schema files to be hosted on http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2:

<xs:import namespace="http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/vuln" schemaLocation="**http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/vuln.xsd**"/><xs:import namespace="http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/common" schemaLocation="**http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/common.xsd**"/><xs:import namespace="http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/prod" schemaLocation="**http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/prod.xsd**"/>

This breaks validation because the files are not available on this location. It would be either required to publish the schema files at 

http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/

or to change cvrf.xsd to point to the real location of the XSD files: 

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/

**Comment by santosomar** [comment]
The best approach will be to change cvrf.xsd to point to the real location of the XSD files:

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas

We will discuss in the TC meeting today (2019-06-26) and will edit the file accordingly.

**Comment by santosomar** [comment]
The correct location is documented at:

http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/cvrf

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/common.xsd 

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/cvrf.xsd

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/prod.xsd

http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/vuln.xsd

**Comment by santosomar** [comment]
Fixed by https://github.com/oasis-tcs/csaf/commit/d4e24afd326668ce891a53ceed99cece5c801e07

**Comment by santosomar** [comment]
@constcast  - please verify https://github.com/oasis-tcs/csaf/commit/d4e24afd326668ce891a53ceed99cece5c801e07

**Comment by sdrees** [comment]
Suggest to remove the extra h 😄

**Comment by santosomar** [comment]
> Suggest to remove the extra h 😄

Thank you @sdrees ! I fixed the typo with https://github.com/oasis-tcs/csaf/commit/430cc98ba3ea524f9cb0ab8986b8e0a04e518ab2

Thanks again!
Omar
