### ISSUE TITLE
Review of the CSAF 2.0 Documentation "Conformance" Section

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/csaf#140]
As discussed in the CSAF TC September 2020 monthly meeting, this issue has been opened to help the TC review the CSAF 2.0 Documentation Draft "Conformance" Section (section 5).

I have included the contents of the section below to help the review process. Please provide any comments directly to this issue.

# 5 Conformance
## 5.1 Conformance Targets
This document defines requirements for the CSAF file format and for certain software components that interact with it. The entities ("conformance targets") for which this document defines requirements are:
* **CSAF document**: A security advisory text document in the format defined by this document.
* **CSAF producer**: A program which emits output in the CSAF format.
* **Direct producer**: An analysis tool which acts as a CSAF producer.
* **Converter**: A CSAF producer that transforms the output of an analysis tool from its native output format into the CSAF format.
* **CSAF post-processor**: A CSAF producer that transforms an existing CSAF document into a new CSAF document, for example, by removing or redacting security-sensitive elements.
* **CSAF consumer**: A program that reads and interprets a CSAF document.
* **Viewer**: A CSAF consumer that reads a CSAF document, displays a list of the results it contains, and allows an end user to view each result in the context of the artifact in which it occurs.
* **Result management system**: A software system that consumes the documents produced by analysis tools, produces reports that enable engineering teams to assess the quality of their software artifacts at a point in time and to observe trends in the quality over time, and performs functions such as filing bugs and displaying information about individual results.
* **Engineering system**: A software development environment within which analysis tools execute. It might include a build system, a source control system, a result management system, a bug tracking system, a test execution system, and so on.
The normative content in this document defines requirements for CSAF documents, except for those normative requirements that are explicitly designated as defining the behavior of another conformance target.

## 5.2 Conformance Clause 1: CSAF document
A text file satisfies the "CSAF document"”" conformance profile if:
* It conforms to the syntax and semantics defined in section 3.

## 5.3 Conformance Clause 2: CSAF producer
A program satisfies the "CSAF producer" conformance profile if:
* It produces output in the CSAF format, according to the semantics defined in section 3.
* It satisfies those normative requirements in section 3 that are designated as applying to CSAF producers.

## 5.4 Conformance Clause 3: Direct producer
An analysis tool satisfies the "Direct producer" conformance profile if:
* It satisfies the "CSAF producer" conformance profile.
* It additionally satisfies those normative requirements in section 3 that are designated as applying to "direct producers" or to "analysis tools".
* It does not emit any objects, properties, or values which, according to section 3, are intended to be produced only by converters.

## 5.5 Conformance Clause 4: Converter
A converter satisfies the “Converter” conformance profile if:
* It satisfies the "CSAF producer" conformance profile.
* It additionally satisfies those normative requirements in section 3 that are designated as applying to converters.
* It does not emit any objects, properties, or values which, according to section 3, are intended to be produced only by direct producers.

## 5.6 Conformance Clause 5: CSAF post-processor
A CSAF post-processor satisfies the "CSAF post-processor" conformance profile if:
* It satisfies the "CSAF consumer" conformance profile.
* It satisfies the "CSAF producer" conformance profile.
* It additionally satisfies those normative requirements in section 3 that are designated as applying to post-processors.

## 5.7 Conformance Clause 6: CSAF consumer
A consumer satisfies the "CSAF consumer" conformance profile if:
* It reads CSAF documents and interprets them according to the semantics defined in section 3.
* It satisfies those normative requirements in section 3 that are designated as applying to CSAF consumers.

## 5.8 Conformance Clause 7: Viewer
A viewer satisfies the "viewer" conformance profile if:
* It satisfies the "CSAF consumer" conformance profile.
* It additionally satisfies the normative requirements in section 3 that are designated as applying to viewers.

## 5.9 Conformance Clause 8: Result management system
A result management system satisfies the "result management system" conformance profile if:
* It satisfies the "CSAF consumer" conformance profile.
* It additionally satisfies the normative requirements in section 3 and Appendix B ("Use of fingerprints by result management systems") that are designated as applying to result management systems.

## 5.10 Conformance Clause 9: Engineering system
An engineering system satisfies the "engineering system" conformance profile if:
* It satisfies the normative requirements in section 3 that are designated as applying to engineering systems.

(Note: The [OASIS TC Process](https://www.oasis-open.org/policies-guidelines/tc-process#wpComponentsConfClause) requires that a specification approved by the TC at the Committee Specification Public Review Draft, Committee Specification or OASIS Standard level must include a separate section, listing a set of numbered conformance clauses, to which any implementation of the specification must adhere in order to claim conformance to the specification (or any optional portion thereof). This is done by listing the conformance clauses here.
For the definition of "conformance clause," see [OASIS Defined Terms](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2017-05-26#dConformanceClause).

See "Guidelines to Writing Conformance Clauses":  
http://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html.

Remove this note before submitting for publication.)

**Comment by mprpic** [comment]
This might be a stupid question, but what is the purpose of this section? Who is the intended audience for this text? Is it simply to be able to name particular parts of a CSAF pipeline with appropriate terms? For example, if I create a tool that outputs CSAF documents, I can call it a "CSAF producer" if it conforms to the rules defined in section 5.3?

**Comment by sthagen** [comment]
The intended audience is the reader of the specification. This is a normative OASIS section that empowers producers of implementations to claim specific conformance of these implementations with the standard and the acquirer to validate such claimed conformance. We can use it as a marketing instrument to lower the entry hurdles for implementers and we can profit from (the agreed upon version) as it fosters interoperability across the sharing communities. The specific wording and "profiles" we decide are up to us (the TC members).
@mprpic : Yes, to answer the question: THat would be a goal; if there is a conformance "profile" / section stating a "XYZ producer" with requirements stated, then some tool fulfilling those can claim to be a conforming "XYZ producer".

**Comment by tschmidtb51** [comment]
Thanks for the work.

I would like to raise the question whether we should also define:

- **CVRF CSAF converter** (converts CVRF to CSAF): This might be helpful if we define default behaviors for converter where things changed between CVRF and CSAF.
- **CSAF Management System** (extends a Viewer by managing multiple CSAF documents)
- **Asset matching system** (extends a Viewer / Management system by the functionality that it is able to match CSAF document (with a probability) to items of an asset database)

**Comment by tschmidtb51** [comment]
Shouldn't we include into the conformance targets also section 4 (at least for CSAF producer and consumer)?

**Comment by sthagen** [comment]
> Shouldn't we include into the conformance targets also section 4 (at least for CSAF producer and consumer)?

Yes from my point of view also for the suggestion from @mprpic - but it would help a lot, when we actually use these roles in the sections we are referring to :wink:

As noted, I borrowed that structure of „participants“ directly from our SARIF OASIS standard where we use the in action (not only in the glossary). Let us discuss this please during the next TC meetings esp. which roles seem meaningful given the TC members experience in production and how we want to anchor those roles inside sections 3 and 4..

**Comment by tschmidtb51** [comment]
I created a new ticket which suggests new conformance targets to provide guidance how and where an end user should find CSAF documents: see #152

**Comment by tschmidtb51** [comment]
I removed CSAF translator and CSAF modifier from #152 and pasted them here since they base on the definition of CSAF producers. Therefore, they are not related to the question where to find CSAF documents.

---

- **CSAF modifier**: provides CSAF documents which base on CSAF documents which have been published by another CSAF publisher.
> Idea: A company might want to share with their customers a in-depth or branch / sector specific analysis which takes the context in to account. It takes the original CSAF and produces a new one which also includes its information.

- **CSAF translator**: translates a CSAF document from one language into another. See #156 for details.
> Idea: Not everyone speaks English. Government might be required to issue advisories in more than one language.

**Comment by tschmidtb51** [comment]
> It additionally satisfies those normative requirements in section 3 that are designated as applying to "direct producers" or to "analysis tools".

@sthagen: Do we need to put all the requirements for the conformance targets into section 3 or can we do this in an extra section (or even section 5 directly within the conformance clauses)?

I think it adds additional complexity to section 3 which doesn't help when you only want to use the standard. I like the idea to have it all in one place. However, it might be easier for the readers to understand the CSAF documents if they are not "distracted by implementation rules".

**Comment by sthagen** [comment]
> > It additionally satisfies those normative requirements in section 3 that are designated as applying to "direct producers" or to "analysis tools".
> 
> @sthagen: Do we need to put all the requirements for the conformance targets into section 3 or can we do this in an extra section (or even section 5 directly within the conformance clauses)?
> 
> I think it adds additional complexity to section 3 which doesn't help when you only want to use the standard. I like the idea to have it all in one place. However, it might be easier for the readers to understand the CSAF documents if they are not "distracted by implementation rules".

In my experience any initial theoretical separation between why and what as well as what and how becomes a balanced overlap in practice.

The proposal is to mix roles into the implementation section 3 where applicable and then reference these in the conformance section as a summary. This also gives a nice hint which roles are YAGNI - namely when they do not naturally appear in the implementation section.

On the other hand there maybe practically important roles that are pure component wrappers - holding two or more essential roles and combining these in meaningful operation. Those can easily be exposed in a conformance section by stating the obvious aggregation of their ingredient roles or - in case the practical experience from the members of the committee shows this - also the not so obvious aggregation.

It is still early after the winter break, so I may have not made myself clear or it is not convincing :wink: ...

**Comment by tschmidtb51** [comment]
In my understanding, we a currently missing a definition what a system should (at least) support which is used by a vendor to create CSAF documents. Therefore, I suggest the **CSAF content management system**. See #183 for details.

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51: In case we accept the proposals of the individual issues adding conformance targets(which I all second in those respective tickets) I can merge the texts to build a new conformance section, amend section 3 for the score preferences,  and will at least add all missing entries into the terminology section.

ETA: when we decide to go this way today during the meeting, I can have a new editor revision ready within two weeks. That would leave all members two weeks for review before the next meeting.

**Comment by santosomar** [comment]
Thank you! I have this in the agenda for today's meeting.

**Comment by santosomar** [comment]
During the TC's monthly meeting on Feb 24, 2021, it was decided and voted that the following two items will be removed from the proposed standard:
```
- Result management system: A software system that consumes the documents produced by analysis tools, produces reports that enable engineering teams to assess the quality of their software artifacts at a point in time and to observe trends in the quality over time, and performs functions such as filing bugs and displaying information about individual results.

- Engineering system: A software development environment within which analysis tools execute. It might include a build system, a source control system, a result management system, a bug tracking system, a test execution system, and so on.
The normative content in this document defines requirements for CSAF documents, except for those normative requirements that are explicitly designated as defining the behavior of another conformance target.
```

**Comment by santosomar** [comment]
The following issues have been approved during the TC's monthly meeting on Feb 24, 2021.
- #164 #183 #172 #168 #165

**Comment by tschmidtb51** [comment]
I suggest to close the ticket.
