### ISSUE TITLE
Conformance target CSAF translator

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#156]
This issue is meant to tidy up the suggestion of the conformance target **CSAF translator** proposed in  ~~#152~~ #140. 

## 5.1 Conformance Targets

- **CSAF translator**: A CSAF post-processor which takes a CSAF document as input and translates values of properties into another language. The output is a valid CSAF document.

## 5.Y Conformance Clause Y-1: CSAF translator

A program satisfies the "CSAF translator" conformance profile if:
- It satisfies the "CSAF post-processor" conformance profile.
- It additionally satisfies those normative requirements in section 3 that are designated as applying to CSAF translators.
- It doesn't add or remove other elements than required by section 3.
- It translates at least one value.
- The translation must be of the same contents and form.

---

In section 3, we need to add the conversion rules: e.g. for
- `document/tracking/id`: The translation must not have the same `id`as the original document.
-  `lang`: must be present and set
- `source_lang`: must contain the language of the original document (and should only be set by CSAF tranlators) 
- `references`: must include a reference to the original advisory (as first element of array), may include translation of given references when keeping them as original source

**Comment by tschmidtb51** [comment]
Red Hat states in their advisory that a modified version "must provide attribution to Red Hat Inc.". We could think about whether this also applies here and a translator should acknowledge the original issuer.

**Comment by tschmidtb51** [comment]
It is important to (be able to) differentiate between a **CSAF translator** (which must not change the content) and **CSAF modifier** (which changes the content; see #164).

**Comment by sthagen** [comment]
Looks good to me and I understand the `CSAF Translator` As a constrained `CSAF Processor` (My fingers have trouble typing Modifier :wink:

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51:  In case we accept the proposal (which I second) I can add the text to the conformance section, amend section 3 as needed, and will at least add an entry into the terminology section.

**Comment by santosomar** [comment]
This issue was approved during the CSAF TC monthly meeting on Feb 24, 2021.
