### ISSUE TITLE
Conformance target CSAF modifier

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#164]
This issue is meant to tidy up the suggestion of the conformance target **CSAF modifier** proposed in ~#152~ #140.

## 5.1 Conformance Targets
- **CSAF modifier**: A CSAF post-processor which takes a CSAF document as input and modifies the structure or values of properties. The output is a valid CSAF document.

## 5.Z Conformance Clause Z-1: CSAF modifier

A program satisfies the "CSAF modifier" conformance profile if:
- It satisfies the "CSAF post-processor" conformance profile.
- It additionally satisfies those normative requirements in section 3 that are designated as applying to CSAF modifiers.
- It adds, deletes or modifies at least one property or object or value of a property.
- It does not emit any objects, properties, or values which, according to section 3, are intended to be produced only by CSAF translators.
---

In **section 3**, we need to add the modification rules: e.g. for
- `document/tracking/id`: The modification must not have the same `id` as the original document.
- `references`: must include a reference to the original advisory (as first element of array)

**Comment by tschmidtb51** [comment]
Unlike the **CSAF translator** (see #156) the **CSAF modifier** should change the content. It might add value to the advisory by adding sector- or even company-specific (if it is implemented at a local CERT of an asset owner) information.

**Comment by sthagen** [comment]
I am still not happy with the name part `modifier ` but otherwise this looks good to me and close to implementable.  Why dońt we name it `CSAF Processor`?

**Comment by tschmidtb51** [comment]
> I am still not happy with the name part `modifier ` but otherwise this looks good to me and close to implementable. Why dońt we name it `CSAF Processor`?

`CSAF processor` seems to be misleading as the specified target is a "child" of the `CSAF post-processor`. Naturally, I would assume having a `processor` in front of a `post-processor`.

Could you please explain a bit more why you're unhappy with the part `modifier`? It is a program which modifies an existing CSAF document so I thought `CSAF modifier` seems natural. However, I'm open for a better name...

**Comment by sthagen** [comment]
Sorry, completely lost the post processor. I will visit the new zoo again and try to better grok what the names and capability say then - modify is too neutral in my perception, that is why I suggested processor in the first place. But this does not suit post-processor animal. 👍🏽 
CSAF Filter could match, but than the post-processor sounds like the ugly uncle.
One problem with naming is often mixing perspectives, which we do here, right?
Another is over generalization when single nouns are chosen and become unclear to different people in what these exactly stand for.

But, have to do my homework first then will come back to the namings.

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51:  Are we all good with the "modifier" term?
In case we accept the proposal (which I would second if the TC agrees on the naming) I can add the text to the conformance section, amend section 3 as needed, and will at least add an entry into the terminology section.

**Comment by santosomar** [comment]
This issue was approved during the CSAF TC monthly meeting on Feb 24, 2021.
