### ISSUE TITLE
Conformance target CSAF viewer

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#165]
This issue is meant to provide more details to the conformance target **CSAF viewer** proposed in #140. It also recommends to add the CSAF up front.

## 5.1 Conformance Targets
- **CSAF viewer**: A CSAF consumer that reads a CSAF document, displays a list of the results it contains, and allows an end user to view each result in the context of the artifact in which it occurs.

## 5.8 Conformance Clause 7: CSAF viewer
A CSAF viewer satisfies the "CSAF viewer" conformance profile if:

- It satisfies the "CSAF consumer" conformance profile.
- It additionally satisfies the normative requirements in section 3 that are designated as applying to viewers.
- The result must be readable by an end user.

---

In **section 3**, we need to add the rules: e.g. for
- `scores`: 
   - give preference to CVSS `vector` if it doesn't match the attributes
   - give preference to CVSS `vector` if it doesn't match the `baseScore` and `baseSeverity`

**Comment by sthagen** [comment]
Looks good to me and ready for implementation.

**Comment by sthagen** [comment]
In case we accept the proposal (which I second) I can add the text to the conformance section, amend section 3 for the score preferrences,  and will at least add an entry into the terminology section.

**Comment by santosomar** [comment]
This issue was approved during the CSAF TC monthly meeting on Feb 24, 2021.
