### ISSUE TITLE
Conformance target CSAF management system

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#168]
This issue is meant to provide more details to the conformance target **CSAF management system** proposed in #140. 

## 5.1 Conformance Targets
- **CSAF management system**: A program that is able to manage CSAF documents and is able to display their details as required by "CSAF viewer".

## 5.A Conformance Clause A-1: CSAF management system
A CSAF management system satisfies the "CSAF management system" conformance profile if:

- It satisfies the "CSAF viewer" conformance profile.
- It additionally satisfies the normative requirements in section 3 that are designated as applying to management systems.
- It provides at least the following management functions:
   - add new CSAF documents (e.g. from file system or URL) to the system
   - list all CSAF documents within the system
   - delete CSAF documents from the system
   - comment on CSAF documents in the system
   - mark CSAF documents as read in the system
   - search for CSAF documents by values of required fields at `document`-level or their children within the system
   - search for CSAF documents by values of `cve` within the system
   - search for CSAF documents based on properties of `product_tree`
   - filter on all properties which it is required to search for
- It must identify the latest version of CSAF documents with the same `document/tracking/id`
- It must be able to show the difference between 2 versions of a CSAF document with the same `document/tracking/id`.
---
In **section 3**, we need to add the rules: e.g. for
 `tbd`

**Comment by sthagen** [comment]
Looks good to me - section 3 impact we will resolve as we go.

**Comment by sthagen** [comment]
In case we accept the proposal (which I second) I can add the text to the conformance section and will at least add an entry into the terminology section.

**Comment by santosomar** [comment]
This issue was approved during the CSAF TC monthly meeting on Feb 24, 2021.
