### ISSUE TITLE
Anonymous types

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#169]
Here is a list of anonymous types within CSAF 2.0 schema (see also comment in #158):
- Acknowledgment (`acknowledgments_t[]`) 
	- Name of entity being recognized (`names[]`)
	- Contributing organization (`organizations[]`)
	- URL of acknowledgment (`urls[]`)
- Branch (`branches_t[]`)
- Note (`notes_t[]`)
- (Product in `products_t[]`)
- (Product group in `product_groups_t[]`)
- Reference (`references_t[]`)

- Alias (`document/tracking/aliases[]`)
- Version item (`document/tracking/revision_history[]`)

- (Full product name in `product_tree/full_product_names[]`)
- Product group (`product_tree/product_groups[]`)
- (Product_id in `product_tree/product_groups[]/product_ids[]`)
- Relationship (`product_tree/relationships[]`)

- Vulnerability (`vulnerabilities[]`)
	- Score (`vulnerabilities[]/scores[]`)
	- Involvement (`vulnerabilities[]/involvements[]`)
	- Remediation (`vulnerabilities[]/remediations[]`)
	- Entitlement of the remediation (`vulnerabilities[]/remediations[]/entitlements[]`)
	- Threat (`vulnerabilities[]/threats[]`)

**Comment by tschmidtb51** [comment]
The question here is: Should we have a heading for each of those in the prose?

**Comment by sthagen** [comment]
I think we already describe these elements of typed containers sufficiently enough to no have to inject additional headings in the prose.  I would rather invest the time budget in describing the roles instead and then move quickly into progressing the specification to committee specification status as that enables implementers to go ahead safe from IPR issues and with a stable description to follow.

**Comment by tschmidtb51** [comment]
> I think we already describe these elements of typed containers sufficiently enough to no have to inject additional headings in the prose. 

Then, we should remove those additional headings which were already introduced.

**Comment by tschmidtb51** [comment]
Was integrated with #205 into master.
