### ISSUE TITLE
Conformance target CSAF asset matching system

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#172]
This issue is meant to provide more details to the conformance target **CSAF asset matching system** proposed in #140. 

## 5.1 Conformance Targets
- **CSAF asset matching system**: A program that connects to or is asset database and is able to manage CSAF documents as required by "CSAF management system" as well as matching them to assets of the asset database.

## 5.B Conformance Clause B-1: CSAF asset matching system
A CSAF asset matching system satisfies the "CSAF asset matching system" conformance profile if:

- It satisfies the "CSAF management system" conformance profile.
- It is an asset database or connects to one.
- It matches the CSAF documents within the system to the respective assets. _This might be done with a probability which gives the end user the chance to broaden or narrow the results._
- It provides for each product of the asset database a list of matched advisories.
- It provides for each asset of the asset database a list of matched advisories.
- It provides for each CSAF document a list of matched product of the asset database.
- It provides for each CSAF document a list of matched asset of the asset database.
- It provides for each vulnerability within a CSAF document the option to mark matched asset of the asset database as "not remediated", "remediation in progress", "remediation done". _A switch to mark all in the same status may be implemented."_
- It does not bring up a newer revision of a CSAF document as a new match if the remediation for the matched product or asset has not changed.
- It provides at least the following statistics:
  - How many assets were match at that CSAF document
  - How many of them are marked in which of the given status

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51:  In case we accept the proposal (which I second) I can add the text to the conformance section and will at least add an entry into the terminology section.

**Comment by santosomar** [comment]
This issue was approved during the CSAF TC monthly meeting on Feb 24, 2021.
