### ISSUE TITLE
Conformance target CSAF content management system

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#183]
This issue is meant to provide more details to the conformance target **CSAF content management system** proposed in #140. 

## 5.1 Conformance Targets
- **CSAF content management system**: A program that is able to create, review and manage CSAF documents and is able to preview their details as required by "CSAF viewer".

## 5.C Conformance Clause C-1: CSAF content management system
A CSAF content management system satisfies the "CSAF content management system" conformance profile if:

- It satisfies the "CSAF producer" conformance profile.
- It additionally satisfies the normative requirements in section 3 that are designated as applying to content management systems.
- It provides at least the following management functions:
   - create new CSAF documents
   - prefill CSAF documents based on values given in the configuration (see below)
   - checkout old versions of a CSAF document
   - show diff between versions of a CSAF document
   - list all CSAF documents within the system
   - delete CSAF documents from the system 
   - review CSAF documents in the system
   - approve CSAF documents
   - search for CSAF documents by values of required fields at `document`-level or their children within the system
   - search for CSAF documents by values of `cve` within the system
   - search for CSAF documents based on properties of `product_tree`
   - filter on all properties which it is required to search for
   - export of CSAF documents
   - show an autdit log for each CSAF document 
- It must identify the latest version of CSAF documents with the same `document/tracking/id`
- It suggests a `document/tracking/id` based on the given configuration.
- It must support the following workflows:
   - "New Advisory": create a new advisory, request a review, provide review comments or approve it, resolve review comments; if the review approved it (draft->interim), the approval for publication can be requested; if granted (manual or time-based) the advisory is provided for publication (interim -> final)
   - "Update Advisory": open an existing advisory, create new revision & change content (interim), request a review, provide review comments or approve it, resolve review comments; if the review approved it (draft->interim), the approval for publication can be requested; if granted (manual or time-based) the updated advisory is provided for publication (interim -> final)
- The publication may be immediately or at a given date/time.
- The handling of date/time and version must be automated.
- It must provide an API to retrieve all CSAF documents which are currently in the status published.
- It should provide an API to import or create new advisories from outside systems (e.g. bug tracker, CVD platform,...).
- It must provide a user management and support at least the following roles:
   - _Registered_: Able to see all published CSAF documents (but only in the published version).
   - _Author_: inherits _Registered_ permissions and also can Create and Edit Own (mostly used for automated creation, see above)
   - _Editor_: inherits _Author_ permissions and can Edit (mostly used in PSIRT)
   - _Publisher_: inherits _Editor_ permissions and can Change state and Review any (mostly used as HEAD of PSIRT or team lead)
   - _Reviewer_: inherits _Registered_ permissions and can Review advisories assigned to him (might be a subject matter expert or management)
   - _Manager_: inherits _Publisher_ permissions and can Delete; User management up to _Publisher_
   - _Administrator_: inherits _Manager_ permissions and can Change the configuration
- It may use groups to support client separation (multitenancy) and therefore restrict the roles to actions within their group. In this case, there must be a _Group configurator_ which is able to change the values which are used to prefill fields in new advisories for that group. He might also do the user management for the group up to a configured level.
- It prefills the following fields in new CSAF documents:
   - `document/csaf_version` with the value `2.0`
   - `document/language`
   - `document/notes`
      - `legal_disclaimer` (Terms of use)
      - `general` (General Security recommendations)
   - `document/tracking/current_release_date` with the current date
   - `document/tracking/generator` and children
   - `document/tracking/initial_release_date` with the current date
   - `document/tracking/status`with `draft`
   - `document/tracking/version` with `0.1`
   - `document/publisher` and children
   - `document/type` (based on the templates from configuration)

---
In **section 3**, we need to add the rules: e.g. for
- prefills (see above)
- updating `document/tracking/version`
 `tbd`

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51: In case we accept the proposal (which I second) I can add the text to the conformance section, amend section 3 for the score preferences,  and will at least add an entry into the terminology section.

**Comment by santosomar** [comment]
This issue was approved during the CSAF TC monthly meeting on Feb 24, 2021.
