### ISSUE TITLE
Unique Product IDs in Product groups 

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#189]
Currently, it is allowed to have the same `product_id` twice in the list of `product_ids` in one product group element. See example below:
```
"product_groups": [
      {
        "group_id": "CSAFGID-0001",
        "product_ids": [
          "CSAFPID-0001",
          "CSAFPID-0001"
        ]
      }
```

However, this violates the rule [CSAF-5.1.4.1.2-1](https://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-cs01.html#_Toc493508910). Therefore, I suggest to add an `"uniqueItems": true`.

**Comment by sthagen** [comment]
I consider this a consistency bug and merely editorial to fix. Will request accordingly in corresponding PR
