### ISSUE TITLE
Alphabetical order of properties

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#192]
During the process, we mixed up the order of the properties in the JSON schema. I suggest to rearrange them in alphabethical order. The JSON key words will still be in the order of https://github.com/oasis-tcs/csaf/issues/110#issuecomment-689148217.
```
    _$comment (to be removed before publication)_
    title
    description
    type / $ref
    default
    enum
    format
    pattern
    maxLength
    minLength
    maxItems
    minItems
    maxProperties
    minProperties
    required
    uniqueItems
    properties
    items
    examples
```

**Comment by sthagen** [comment]
@tschmidtb51 very helpful. Looking forward to the PR, as merging this before I inject the conformance targets and their anchors/hooks because then the members can more easily separate formal changes (ordering) from content changes (conformance targets on roles).

**Comment by tschmidtb51** [comment]
@sthagen: Sorry about the delay. Please have a look at the PR #194.
