### ISSUE TITLE
Add Name to Publisher

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#201]
I think we should add a property `name` to `/document/publisher`.

**Reasoning**: We would like to create a format which is machine-readable but also should support the generation of a human-readable version of the document. Currently, we have no place to put the name of the document issuer into.

As the examples show (and also the prose) `contact_details` and `issuing_authority` are not the right place to retrieve this information and use it in a different place / context:

      "contact_details": "Emergency Support:\n+1 877 228 7302 (toll-free within North America)\n+1 408 525 6532 (International direct-dial)\nNon-emergency Support:\nEmail: psirt@cisco.com\nSupport requests that are received via e-mail are typically acknowledged within 48 hours.",
      "issuing_authority": "Cisco product security incident response is the responsibility of the Cisco Product Security Incident Response Team (PSIRT). The Cisco PSIRT is a dedicated, global team that manages the receipt, investigation, and public reporting of security vulnerability information that is related to Cisco products and networks. The on-call Cisco PSIRT works 24x7 with Cisco customers, independent security researchers, consultants, industry organizations, and other vendors to identify possible security issues with Cisco products and networks.\nMore information can be found in Cisco Security Vulnerability Policy available at http://www.cisco.com/web/about/security/psirt/security_vulnerability_policy.html",

This can't be used at a place like:

- document footer of a pdf
- document meta-data of a pdf
- acknowledgment section

Example:

```
     "acknowledgments": [
      {
        "names": [
          "Johann Sebastian Bach"
        ],
        "organizations": [
          "Baroque composers"
        ]
      }
```

should be transformed to

Acknowledgments
{{/document/publisher/name}} thank the following parties for their efforts:

-    Johann Sebastian Bach from Baroque composers

**Comment by mprpic** [comment]
Sounds good to me!
