### ISSUE TITLE
Add translator as option for type of publisher

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#202]
We introduced the conformance target CSAF translator. However, the current publisher type model requires them to have the value `other` for `/document/publisher/type`.

I suggest to add the option `translator` and make it mandatory for translators.

**Comment by mprpic** [comment]
Makes sense!

I can't think of an easy way to tie `source_lang` to `type:translator` so perhaps this could be another candidate for a validation test as proposed in #195.
