### ISSUE TITLE
Change Hash default and names

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#208]
@tolim stated in https://github.com/oasis-tcs/csaf/pull/199#commitcomment-49170069:

> `SHA-3` is ambiguous, as the bit length is not specified. Should we reference the IANA Named Information Hash Algorithm Registry here? https://www.iana.org/assignments/named-information/named-information.xhtml

---

@sthagen replied in https://github.com/oasis-tcs/csaf/pull/199#commitcomment-49171473:

> Yes, I think reusing the ids from the iana registry is much better. I will propose using the bitlengths matching the „other“ sha algorithms and maybe use sha-256 as default instead, because we will not want to edufy the producers but instead offer a meaningful default matching many existing uses already.

---

@tolim stated in https://github.com/oasis-tcs/csaf/pull/199#commitcomment-49180351:

> After a little bit of thought, I suggest to do it differently: we do not require a cryptographically secure hash algorithm here. In contrast, quite many file hashes are available based on MD5 or SHA-1, and the IANA Named Information Hash Algorithm Registry does not list those algorithms. The IANA Hash Function Textual Tables (https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml) would list those, but not the newer ones.
> 
> After looking a bit around, I found the best way to get a good list of hash identifiers is to look at OpenSSL. The command `openssl dgst -list` (Version 1.1.1f from 2020-03-31) outputs the following:
> 
> ```
> Supported digests:
> -blake2b512                -blake2s256                -md4                      
> -md5                       -md5-sha1                  -ripemd                   
> -ripemd160                 -rmd160                    -sha1                     
> -sha224                    -sha256                    -sha3-224                 
> -sha3-256                  -sha3-384                  -sha3-512                 
> -sha384                    -sha512                    -sha512-224               
> -sha512-256                -shake128                  -shake256                 
> -sm3                       -ssl3-md5                  -ssl3-sha1                
> -whirlpool      
> ```
> 
> If there is not a better source available, I would suggest to use those identifiers for the moment.
> 
> As for the default value, I agree to use sha256.

---

As this is something which needs more discussion I added it as a ticket.

**Comment by tschmidtb51** [comment]
Personally, I always prefer a cryptographic secure hash algorithm and I don't like setting the default low when it comes to security - therefore I suggested the `SHA-3`.

However, it is true that many projects (at the moment) only provide `SHA256` or `MD5` hashes for files. Therefore, I agree that we could change the default to `SHA256`.

**Comment by tschmidtb51** [comment]
Btw: We don't allow `MD5` and `SHA1` at the moment because the regex pattern prevents that:

```
                 "value": {
                    "title": "Value of the cryptographic hash",
                    // ...
                    "minLength": 64,
                    "pattern": "^[0-9a-fA-F]{64,}$",
                    // ...
                  }
```

`MD5` has a length of 32. `SHA1` has a length of 40. `SHA256` has a length of 64.

**Comment by sthagen** [comment]
Thinking of use cases for hashes ... we might even allow 16 character long hex representations.
Hashing as a fast filter on probable matches can be important when scanning slow device interfaces with large numbers of files.
As a consumer, I want to err on the safe side, so any plausible match may indicate with enough confidence, that I may need to act.
Hashing as a certification may not be the only use case.

**Comment by tschmidtb51** [comment]
Hmm... I understand the idea. However, as a consumer I could also shorten the hash for my "fast filter" routine. If I store such values in my asset database I could to the same. But if I only get the first 16 characters of a hash from the issuer of the advisory, I can't do a full / complete comparison. I would suggest to provide as many information to the consumer as possible so that they can decide what to do. Information not provided by the issuer can't be used at the consumer, but consumer could always ignore information provided. ;-)

**Comment by sthagen** [comment]
Ah, sorry, I did not suggest truncating hashes, but instead offering hashes instead of cryptographic hashes.

There are ELF & Co. which are very fast and other 64 bit hash algorithms that can act as  probable filters which would require 8 or 16 hex chars for transport in our field so the suggestion is to shorten the pattern and have us not push the users in using a cryptographic hash function. 

So, to emphasize a best effort identification and not certification task.

When a vendor provides md5 hashes for vulnerable binaries, I do not really see a threat scenario, where a collision can cause real problems, because collisions only yield unneeded remediation, right? And, the vendor should have hashed all binary variations in active deployment and herself should switch to a different hash algorithm, in case a collision really happens.

**Comment by tschmidtb51** [comment]
> There are ELF & Co. which are very fast and other 64 bit hash algorithms that can act as probable filters which would require 8 or 16 hex chars for transport in our field so the suggestion is to shorten the pattern and have us not push the users in using a cryptographic hash function.

I have 2 questions here:
- Can these algorithms be used to identify a file? (You wrote something about filters and IMHO that is not what the product_identification_helper was meant to be...)
- Is this already in use? If not, I would probably stick to the things which are already known and used.

> When a vendor provides md5 hashes for vulnerable binaries, I do not really see a threat scenario, where a collision can cause real problems, because collisions only yield unneeded remediation, right? 

We don't only use the hashes for vulnerable products but also to identify fixed ones. A collision in this case could cause serious harm if you think you have the patched version but really you got one with the same hash from a threat actor.

> And, the vendor should have hashed all binary variations in active deployment and herself should switch to a different hash algorithm, in case a collision really happens.

Well, they should - but do all of them do this? And even if they do: Since the filename can be handled as an informational property, this could easily lead to cross-vendor problems.

**Comment by sthagen** [comment]
Well, the advisory comes from a trusted source and states eg. the binary with the md5 so and so is good or not.
The recipient has installed it once or will retrieve it from a trusted source (if it is the fixed one).

If vendor and consumer agree on md5 why should they not use CSAF?

A filter to me is an identifactor that accepts false positives but will never suffer from false negatives.
This can be very useful when asset management is not perfect and one wants to screen the assets fast.

**Comment by tolim** [comment]
16 character long hex representations store values of 64 bit length. Due to the birthday paradox, I would consider this length too small for practical applications if we want to prevent false positive matches with a reasonable probability. 

But I agree with @sthagen and would vote for more freedom for CSAF producers here: it should be their decision which hash functions to use, as they know their environment best. So I suggest to also allow smaller hash values down to 32 bit length, i.e. 8 hex chars. We also should not restrict the allowed algorithms to a defined set. However, we can give recommendations.
