### ISSUE TITLE
Add remark on hash match but filename deviation

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#209]
@tlimmer stated in https://github.com/oasis-tcs/csaf/pull/199#commitcomment-49170258:

> What happens if the hash matches but the file name is incorrect?

---

@sthagen replied in https://github.com/oasis-tcs/csaf/pull/199#commitcomment-49171722:

> To me the ideal case is all-three-match. Another interesting use case IMO is where the file name information is more a comment and the consumer might act on the hash and document internally the deviation in name. Say, an admin renamed a file to not override upon update, created links, or the filesystem did name mappings (case sensitivity/or-not comes to mind and also automatic versioning like renamings as in windows and mac when the user is prompted upon placing a file with colliding name to replace an existing file or not ...

---

@tolim replied in https://github.com/oasis-tcs/csaf/pull/199#commitcomment-49181517:

> Yes, I agree. Using this method of identification, we will always be able to construct cases that will produce false positive matches.
> I would suggest that, if the hash is specified, it should be the sole criteria to decide on. Then the accompanying file name should be informative, and maybe even defined as an optional property.

---

As this is something which needs more discussion I added it as a ticket.

**Comment by tschmidtb51** [comment]
I agree with @sthagen that the ideal case is all-three-match.

I suggest to add a remark that the hash value should be preferred in such situations:

```suggestion
If the value of the Value of the cryptographic hash matches and the Filename does not, a user should prefer the hash value. In such cases the filename should be used an informational property.
```

IMHO, I would refrain from making the file name optional as there is the motion (see #208) to allow weak hash algorithms. This would lead to too many false positives.

**Comment by sthagen** [comment]
Editorial nit:
> ```
> If the value of the hash matches and the Filename does not, a user should prefer the hash value. In such cases the filename should be used as informational property.
> ```

Question: Could that filename property then also be used as a range identifier? Like `bytes_[123,4200]`?

**Comment by sthagen** [comment]
Another idea:
> Offer an array of hash values.

Benefits: 
* producer offers either multiple algorithm values not knowing which of these the consumer prefers or is capable of using
* across versions variations of same name files exist that are vulnerable and others which are not; this way the producer can state hashes vor all known impacted files

Good idea, bad idea? Any feedback appreciated - e.g. to spawn of another low priority issue ...

**Comment by tschmidtb51** [comment]
> Could that filename property then also be used as a range identifier? Like `bytes_[123,4200]`?

Currently, I can't imagine a use case for this. Does anyone have one?

> Could it be a glob pattern? Like `acme*quux?.dll`?

My question would be: Is this necessary? If you name the file different in different versions then they should be listed as different products. And if we decide to always prefer the hash on match then this seems to be not necessary. Am I missing anything here?

**Comment by tschmidtb51** [comment]
> Another idea:
> 
> > Offer an array of hash values.

Don't we already do this? We have a list of hashes. The only difference is that a producer would have to state the Filename multiple time which IMHO makes sense when it can be treated as "more of an informational property".

**Comment by sthagen** [comment]
On the array of hash values per one filename field I think the similarity with the hash offering upon delivery of the product is motivating. Downloads offering md5, sha256, and sha512 checksums, might naturally lead to an advisory offering the same three values per filename and not three entries of identical filenames with respective hashes.

More a vendor, consumer question - just wanted to point out, that multiple hash values per file is more practice than theory.

**Comment by tschmidtb51** [comment]
@sthagen: Thanks for clarifying.

This is a valid use case for me.

**Comment by tolim** [comment]
> > Could that filename property then also be used as a range identifier? Like `bytes_[123,4200]`?
> 
> Currently, I can't imagine a use case for this. Does anyone have one?

No, not in our use case of providing an advisory.

> > Could it be a glob pattern? Like `acme*quux?.dll`?
> 
> My question would be: Is this necessary? If you name the file different in different versions then they should be listed as different products. And if we decide to always prefer the hash on match then this seems to be not necessary. Am I missing anything here?

We should be careful not to make this topic too complex. There are other tools that will do this job in a better way (e.g. Yara https://virustotal.github.io/yara/, Styx https://oasis-open.github.io/cti-documentation/) that can be referenced, so let's stay simple.
