### ISSUE TITLE
Proposal to rename type properties to category

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#212]
CSAF currently exposes enumerations as type properties in some objects.

Examples are in document and in publisher as well as others. A handful.

I propose to instead name that field `category`.

Rationale: The values of these domains are categorial data. There is no ordering implied and the values are all of type string.

Also, we would gain some cognitive separation from the type fields of the core vocabulary of JSON Schema, which would help implementers and users alike IMO.

**Comment by tschmidtb51** [comment]
According to my quick search that would affect the following elements:
```
/definitions/branches_t[]/type
/definitions/notes_t[]/type
/definitions/references_t[]/type 
/document/publisher/type
/document/type
/vulnerabilities[]/remediations[]/restart_required/type
/vulnerabilities[]/remediations[]/type
/vulnerabilities[]/threats[]/type
```

Potentially, we should also apply it to `/product_tree/relationships[]/relationship_type`.

**Comment by sthagen** [comment]
> Potentially, we should also apply it to `/product_tree/relationships[]/relationship_type`.

Yes, the path reads nicely as `product_tree/relationships[]/category`

**Comment by tschmidtb51** [comment]
I think the TC should vote on that. I'm happy to provide the PR afterwards.

@santosomar: Please add it to the agenda.
