### ISSUE TITLE
Clarify the definition of status `interim`

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#226]
During the review of #205 there were some comments regarding the definitions for the `/document/status` value `interim`. The current definition is provided to ease the discussions:

> The value `final` indicates, that the issuing party asserts the content is unlikely to change. “Final” status is an indication only, and does not preclude updates.
>
> The value `interim` indicates, that the issuing party asserts the content is unlikely to change.

---

@tschmidtb51 comment in https://github.com/oasis-tcs/csaf/pull/205#discussion_r612818475:

> @sthagen: This looks like the same definition as `final`. I would suggest the following:
> ```suggestion
> The value `interim` indicates, that the issuing party asserts the content of the current version is unlikely to change. However, further updates of this advisory are already planned.
>```

---

@mprpic replied in https://github.com/oasis-tcs/csaf/pull/205#discussion_r612864616:

> "Content is unlikely to change" and "advisory is planned to be updated" kind of seem like opposite statements. I'm actually not sure what the purpose of the "interim" status is. Either the advisory is in draft and may change, or it's in its final form and is ready for consumption. As a consumer, I'm not sure I would care about a third state when even the "final" state does not mean the content won't ever change again (that's what revision history is for).

---

@sthagen repiled in https://github.com/oasis-tcs/csaf/pull/205#discussion_r612951334:

> I would think of amending an already present content with additional content or measures? But here better practitioners having to produce the incremental versions do speak up.

---

To me, there are 2 options:
1. `interim` is a state which is used for all advisories from the `/document/tracking/initial_release_date` until the issuing party states that no further updates will follow. Then the last advisory gets the status `final`. This would include a change of the definition of `final` to make clear that an advisory, once reached the state final should only be updated in exceptional cases.

   **Pros:** The customer could easily determine whether the issuer intends to update the advisory.
   **Cons:** This could lead to issuers leaving advisories in status `interim` forever :disappointed: 

2. `interim` is a state used in the generation of an advisory as described in conformance target "CSAF content management system" under workflows:

   >- "New Advisory": create a new advisory, request a review, provide review comments or approve it, resolve review comments; if the review approved it (draft->interim), the approval for publication can be requested; if granted (manual or time-based) the advisory is provided for publication (interim -> final)
   >- "Update Advisory": open an existing advisory, create new revision & change content (interim), request a review, provide review comments or approve it, resolve review comments; if the review approved it (draft->interim), the approval for publication can be requested; if granted (manual or time-based) the updated advisory is provided for publication (interim -> final)

   **Pros:** This allows a better coordination during the process of generating an advisory as this might involve the researcher, vendors and coordinating agencies (and sometimes also a user). Moreover, it provides the opportunity to pre-share advisories (e.g. with authorities) before they are final.
   **Cons:** At the moment, I can't think of any.

**Comment by tschmidtb51** [comment]
@santosomar, @mprpic, @tolim: How is this status used currently (e.g. in your company)?

**Comment by sthagen** [comment]
So, from my place „on the mountain in the snow above the clouds“ proposition no. 2 of @tschmidtb51 would be the way to go in case no significantly deviating processing information comes from those members actively producing such advisories.

**Comment by santosomar** [comment]
In short, this is how we use it at Cisco. Interim means that the vulnerability impact is under ongoing investigation and many updates are expected. An example is when we find out about a third party software vulnerability and disclose to the public that we are investigating the impact to Cisco products. Those advisories are typically updated on a daily basis. Then we move into Final once the investigation is over. Could there be any further updates after marking to "Final"? Absolutely, but the likelihood is lower. Hope this helps.

**Comment by mprpic** [comment]
> @santosomar, @mprpic, @tolim: How is this status used currently (e.g. in your company)?

At Red Hat, we only ever publish advisories in their "final" form. We don't share any pre-release information on updates, and once we ship any updates then the advisories for them are considered final (the shipped content never changes and requires a new advisory if it does). If the metadata changes in any way, the CVRF file is updated (though we don't have revision history implemented correctly currently; will be fixed for CSAF 2.0 files).

**Comment by tolim** [comment]
At Siemens, we do it the same as @mprpic is describing for Red Hat. All documents that are published publicly are in status 'final'. So I vote for option #2 in @tschmidtb51's comment.

**Comment by santosomar** [comment]
In our case, when RedHat or an upstream vendor or open source package provider publishes their "final" advisory, our investigation just starts. Thus the beauty of this: https://www.first.org/global/sigs/vulnerability-coordination/multiparty/media/image1.jpg
![image of multiparty vulnerability coordination](https://www.first.org/global/sigs/vulnerability-coordination/multiparty/)

**Comment by zmanion** [comment]
One way to think of this might be about rate of change. "Interim" means author expects frequent changes. "Final" means author expects slow/few changes. Change is allowed no matter what the state. Possibly if no changes happen in a period of time, state should shift to "Final."

**Comment by zmanion** [comment]
From 2021-04-14 meeting: Confirm definition language of "interim" and "final". By default, a CSAF document is status:final. A CSAF author may change to status:interim and the author takes responsibility for changing status back to final at author's discretion. If and when author changes status and how author manages that change is up to author and their CSAF readers.

**Comment by tschmidtb51** [comment]
> By default, a CSAF document is status:final.

Just to make sure: Do you think that we should put that as default value in the schema? Most tools should / will start with `draft`.

However, I agree that in comparison between `final` and `interim` the value `final`should be the default use case.

**Comment by sthagen** [comment]
I also do think a default of final per schema is a too eager choice.
Just because advisories going „out“ are mostly final, this is a very improbable value in the early stages of such a document.
I think for non-binary types a default is often hard to chose for even most use cases.
In this case a tool supporting an author or reviewer of an advisory from begin to end of the workflow would ignore the default I assume and use other measures to suggest a value. Like: Start with suggested draft value, and later when triggering publication actions maybe alerting when the field is not set to final.

Let us not place this default on the schema level, but in prose like a business expectation.

**Comment by zmanion** [comment]
I was mostly capturing the discussion from the meeting and don't have a strong personal recommendation. I agree with the idea that the suggested/expected defaults and changes could be in prose/guidance/documentation, and not baked into the schema, this seems to be a cleaner separation.

**Comment by santosomar** [comment]
I agree. I think that defaults should be left for the tool/implementor to decide. Even if more than 90% of the aforementioned advisories are published as "final". The language/specification should not provide a "default". But perhaps we should make this field mandatory. There should be at least a status being specified? @zmanion We have bounced the idea of using machine readable advisories for vulnerability coordination inside of a company even before being published publicly. Do you see any use cases where this "interim" option could be used by someone like CERT during the investigation and coordination of a vulnerability before is made public?
