### ISSUE TITLE
Proposal for acknowledgments attributes to be single values instead of arrays

### ISSUE THREAD

**Issue by mprpic** [oasis-tcs/csaf#227]
Currently, the schema defines the `acknowledgments_t` type as a list of objects that themselves may contain lists of names and organizations. This may produce valid data such as:

```
acks: [
  {names: [Joe, Mary, Ann], organizations: [BigCorp, CoolStartup]},
]
```

I think the schema should enforce this to be split into multiple objects with the name and organization as single values so that the relationship between a person and their organization is explicit. Alternatively, we could limit just the `organizations` attribute to be a single value so that multiple persons affiliated with the same organization could be specified in a single object, but that seems overly complicated in my opinion.

The above represented as single values would look like this:

```
acks: [
  {name: Joe, organization: BigCorp},
  {name: Mary, organization: CoolStartup},
  {name: Ann}
]
```

The `summary` and `urls` attributes of the acknowledgment object would remain unchanged.

**Comment by tschmidtb51** [comment]
Let me give an example how I would intent to use the current structure:

```
"acknowledgments": [
      {
        "names": [
          "Johann Sebastian Bach",
          "Georg Philipp Telemann",
          "Georg Friedrich Händel"
        ],
        "organizations": [
          "Baroque composers"
        ],
        "summary": "wonderful music"
      },
      {
        "organizations": [
          "CISA"
        ],
        "summary": "coordination efforts",
        "urls": [
          "https://cisa.gov"
        ]
      },
      {
        "names": [
          "Antonio Vivaldi"
        ],
        "summary": "influencing other composers"
      },
      {
        "organizations": [
          "BSI",
          "CERT/CC"
        ],
        "summary": "assistance in coordination"
      }
    ],
```
This should lead in a human-readable advisory to the following outcome:

>We thank the following parties for their efforts:
>
>   - Johann Sebastian Bach, Georg Philipp Telemann, Georg Friedrich Händel from Baroque composers for wonderful music
>   - CISA for coordination efforts (see: https://cisa.gov)
>   - Antonio Vivaldi for influencing other composers
>   - BSI, CERT/CC for assistance in coordination

Having compiled the example, I now also see the problem: If I add a `url` to the last array item, it can't be clear what organization this is for:
```
// ...
      {
        "organizations": [
          "BSI",
          "CERT/CC"
        ],
        "summary": "assistance in coordination",
        "urls": [
          "https://www.bsi.bund.de"
        ]
      }
```

Therefore, I would like to apologize that I haven't seen/ understood this problem before and agree that the `organisations` introduces the trouble.

**Comment by tschmidtb51** [comment]
Long story short: I agree, we should remove the array from `organisations` and make it a single value.
