### ISSUE TITLE
Document tracking artifacts

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/csaf#24]
The fields "document":"tracking":"version" and "document":"tracking":"revision_history" are not listed as required in CSAF 2.0 (https://github.com/oasis-tcs/csaf/blob/master/sandbox/csaf_2.0/json_schema/csaf_json_schema.json) anymore.  We believe that these information are easy to create and maintain and provide huge benefit to the audience. Therefore, the should stay mandatory (as they were in CVRF 1.2).

**Comment by sthagen** [comment]
Suggest to merge the pull request Document tracking artifacts #32 - technically I could do that, but would love to have another approver.
