### ISSUE TITLE
Consider VEX definition alignment for product_status

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/csaf#260]
Original email from Allan:

From: "Friedman, Allan" <AFriedman@ntia.gov>
Reply-To: VEX Subgroup <ntia_sbom_vex@osmmail.ntia.doc.gov>
Date: Monday, May 24, 2021 at 8:47 PM
To: VEX Subgroup <ntia_sbom_vex@osmmail.ntia.doc.gov>
Subject: VEX - finalizing definitions (pls review by 12:01am May 26)

Hi Folks,

We had a productive discussion going through most of the rest of the CSAF fields, and making sure they met our needs for at least a VEX 1.0. Link to the details below with some notes.

We now need to win over the CSAF community for the core definition of VEX: not affected and affected. These currently have a bit of a circular definition, so hopefully, we'll win some friends.

Below are the definitions that we've workshopped. Please review and share any urgent critical comments, ideally with a suggested solution. If anyone wants more background on these, and what we're trying to do, let me know, and I'll give you a few min.

Defining /vulnerabilities[]/product_status

known_not_affected 
No mitigation is required regarding this vulnerability. 
This could be because the code referenced in the vulnerability is not present, not exposed, compensating controls exist, or other factors. 
See /vulnerabilities[]/notes and /vulnerabilities[]/threats for more details

known_affected
Actions are recommended to mitigate or address this vulnerability 
This could include learning more about the vulnerability and context, and/or making a risk- based decision. See /vulnerabilities[]/notes, /vulnerabilities[]/threats, and /vulnerabilities[]/remediations for more details.

Fixed  (definition from current CSAF docs)
These versions contain a fix for the vulnerability but may not be the recommended fixed versions.

Under_Investigation  (definition from current CSAF docs)
It is not known yet whether these versions are or are not affected by the vulnerability. However, it is still under investigation - the result will be provided in a later release of the document.

CSAF / VEX mapping: https://docs.google.com/spreadsheets/d/109NHx0FBkgmgVGrDCKPmj3SitP75_9WeMrtYSEXGGRc/edit#gid=0

**Comment by santosomar** [comment]
These definitions look very good. One minor suggestion: perhaps add the word “remediation” to the known_not_affected definition, as follows:

known_not_affected 
No mitigation or remediation is required regarding this vulnerability. 

The reason of my silly request is because often people refer to a “mitigation” as a workaround and they refer to the ultimate fix as the final “remediation”.

Let's discuss in the TC meeting on May 26, 2021.

**Comment by sthagen** [comment]
@santosomar is the target of this issue VEX or CSAF? I thought the CSAF terms were battle proven and it is only a mapping that is needed to make VEX and CSAF interoperable.

**Comment by santosomar** [comment]
Both, so that they are interoperable and the definitions are not contradicting themselves. The suggestions (IMHO) are very relevant and easy to implement. There is still a lot of discussion on the VEX group right now. However, I'm putting this in the agenda for tomorrow's meeting.

**Comment by allan-ntia** [comment]
@sthagen  - for the VEX concept to work, we need some clarity around what "not affected" actually means, and we're proposing defining it around whether any action might be required or expected.

**Comment by tschmidtb51** [comment]
It is true that CSAF currently lacks a good definition of "affected":

> Known affected (`known_affected`) of value type Products (`products_t`) represents that these versions are known to be affected by the vulnerability.

Therefore, I like the idea of giving some more advise.

**Comment by tschmidtb51** [comment]
> known_not_affected
> No mitigation or remediation is required regarding this vulnerability.

I would suggest to use only *remediation* as `mitigation` is a category in `remediations`:

> No remediation is required regarding this vulnerability.

**Comment by tschmidtb51** [comment]
I just added a suggestion (see #266) to solve the issue. It includes a minor rephrasing to match CSAF use of `mitigation` and `remediation`.
