### ISSUE TITLE
Update examples for each of the elements

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/csaf#27]
Examples should be included for each objects/elements in the CSAF 2.0 schema documentation.

**Comment by tschmidtb51** [comment]
@sthagen I found two other examples which where not numbered yet. See 35eaea6.

**Comment by tschmidtb51** [comment]
@sthagen I guess the best approach to correct the numbering is to wait until #321 and #320 have been merged. Otherwise, there will be merge conflicts.
