### ISSUE TITLE
Publisher namespace

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#275]
During the review of #274 it was suggested to tie the signature to the namespace. Now we have 4 options:

### 1. Allow only (any) URLs in the namespace

This reflects the current implementation of #247. Publisher can use the same namespace as for e.g. SPDX (also a URL). The identity for the signature would have to be done through a newly introduced (mandatory?) property `/document/publisher/contact_details/email`.

### 2. Allow only domain URLs in the namespace

A domain can be used for verification (e.g. through DNS). The DNS ensures that the namespace is unique. However, it might be "hard" for some open source projects if they are small and only hosted at GitHub/GitLab/... (and e.g. distributed through a package manager as npm or pip) to fulfill this requirement.

### 3. Allow only emails in the namespace

Also emails are globally unique. It naturally integrates with the OpenPGP system suggested for signatures. It does not even need to be the same address which the issuing party uses for their communication as it independent from the `contact_details`. However, an email is not typically considered a namespace. 

### 4. Allow all of the options above

This might not be easy to parse. IMHO, I don't like the idea of providing multiple options if there is no pressing need.

**Comment by tolim** [comment]
I vote for option 1.

As to the alternatives:
* Reg. 2: OSS projects will get problems, and I see no reason for this artificial restriction.
* Reg. 3: Why should we deviate from the current practice in the CSAF spec to use URLs for references? I see namespaces somewhat similar to references.
* Reg. 4: I agree. If there is no good reason, let's avoid multiple options. Allowing any URL as namespace already gives enough freedom.

**Comment by tschmidtb51** [comment]
@sthagen commented in https://github.com/oasis-tcs/csaf/issues/267#issuecomment-870800536: 

---

From discussions of the changes in the PR #274 I perceive that the replacement field for `vendor_id` might attract additional and unfortunately diverging semantics. I understand the publisher namespace as a simple anchor to complete the local unique identifier into an ordered pair of identifiers that is globally unique. Others seem to want to use that same publisher namespace value as directly dereferenceable key identifier for key distribution and signature validation of the document itself.

I propose we discourage that second strong coupling to signatures at least for version 2.0 and focus on the main purpose of the publisher namespace. Especially, because (1) that addition fixes a bluff from CVRF 1.2 and earlier (promising semantics that were never practically useful) and (2) as adding the new namespace field IMO brings CSAF closer to typical SBOM formats like CycloneDX and SPDX when it comes to attribution / source identification.

**Comment by sthagen** [comment]
@tschmidtb51  thanks for placing my comment where I should have maybe put it in the first place 😄

**Comment by tschmidtb51** [comment]
With the TC decision to accept #274 today this issue is not longer needed.

If there is a need for coupling signatures to CSAF documents, this should be considered in later version of CSAF.
