### ISSUE TITLE
Find a better place to specify the filename rules

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#277]
@tolim commented in #256: 

We specify the filename of our CSAF document in a quite hidden section under Document Property - Tracking - ID. I would not have expected that as a reader. Can we find some other, more adequate place for this specification so that it can also be found in the TOC?

**Comment by sthagen** [comment]
I started assuming the data to be a network payload where the name on storage will be given by the consumer matching their needs. Typically combining publisher namesake and id of the advisory maybe adding some timestamp for incoming detection of changes in case the publisher (producer) does change the advisory without consistent version updates ... but if for general distribution, navigation support and discoverability such a filename indeed is considered essential we should be able to add to the always present gorilla in the room (the document object) as first level member.
