### ISSUE TITLE
Diagrams and figures should be updated in the CSAF 2.0 schema documentation draft

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/csaf#28]
Diagrams and figures should be updated in the CSAF 2.0 schema documentation draft

**Comment by sthagen** [comment]
@santosomar I propose to close this issue with no action as we do not provide any diagrams or figures with the work product anymore for CSAF 2.0.

The slides and any future visuals may suit better committee notes or other tutorial / marketing material (so it can easily be adjusted to user and market needs).

**Comment by santosomar** [comment]
I completely agree. We can also post those in the CSAF website, as well.
