### ISSUE TITLE
Introduce provider-metadata.json to ease automation

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#289]
While writing the requirements for the CSAF provider I realized that our current suggestion makes it harder for automation than it should be as we offer multiple options which can be served as a CSAF provider. As a user you don't know in advance which option will be used. Therefore, I suggest to link all to a `provider-metadata.json` (instead of either a directory or a ROLIE service document) which will explicitly state also the metadata used later on for the CSAF aggregator.

This would allow to skip the ROLIE Service Document.

Thoughts?

Flag @sthagen, @santosomar, @mprpic, @tolim, @zmanion for attention...

**Comment by santosomar** [comment]
That probably will require TC discussion. Can you send it via email to the TC?

**Comment by sthagen** [comment]
Is this more a constrained vocabulary or do we offer an extension point (to add option values)?

**Comment by tschmidtb51** [comment]
I'll write up an suggestion and provide that as a DRAFT PR and link to that via email.

**Comment by tschmidtb51** [comment]
I added the Draft PR #290. Please comment directly there.
