### ISSUE TITLE
Re-organize Repository Elements

### ISSUE THREAD

**Issue by santosomar** [oasis-tcs/csaf#33]
Re-organize Repository Elements based on feedback in the following thread: https://lists.oasis-open.org/archives/csaf/202005/msg00004.html

**Comment by santosomar** [comment]
Started the reorganization of the repository elements (files and directories) via https://github.com/oasis-tcs/csaf/commit/d279d7e69eda856d14d51c6aaf0a150a1e6d82ce

**Comment by sthagen** [comment]
@santosomar I propose to resolve this issue as done and close without further action.

**Comment by santosomar** [comment]
I agree. This legacy issue has been addressed years ago. Thank you!
