### ISSUE TITLE
Correct links in status section - these point to OpenC2 instead of CSAF TC

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#354]
# Situation / Comment

> Status
>
>   The invitation for public comments on the website 
> 
> https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html
>
> directs to the TC page for OpenC2
> (https://www.oasis-open.org/committees/openc2/)

# Proposal (from review comment)

correct the links in the section status for the next iteration / progression of the draft:

Instead of 

> ### Status:
> 
> This document was last revised or approved by the OASIS Common Security Advisory Framework (CSAF) TC on the above date. The level of approval is also listed above. Check the "Latest stage" location noted above for possible later revisions of this document. Any other numbered Versions and other technical work produced by the Technical Committee (TC) are listed at https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=openc2#technical.
>
> TC members should send comments on this specification to the TC's email list. Others should send comments to the TC's public comment list, after subscribing to it by following the instructions at the "Send A Comment" button on the TC's web page at https://www.oasis-open.org/committees/openc2/.
>
> This specification is provided under the Non-Assertion Mode of the OASIS IPR Policy, the mode chosen when the Technical Committee was established. For information on whether any patents have been disclosed that may be essential to implementing this specification, and any offers of patent licensing terms, please refer to the Intellectual Property Rights section of the TC's web page (https://www.oasis-open.org/committees/openc2/ipr.php).
>
> Note that any machine-readable content (Computer Language Definitions) declared Normative for this Work Product is provided in separate plain text files. In the event of a discrepancy between any such plain text file and display content in the Work Product's prose narrative document(s), the content in the separate plain text file prevails.

write: 

> ### Status
>
> This document was last revised or approved by the OASIS Common Security Advisory Framework (CSAF) TC on the above date. The level of approval is also listed above. Check the "Latest stage" location noted above for possible later revisions of this document. Any other numbered Versions and other technical work produced by the Technical Committee (TC) are listed at https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=csaf#technical.
>
> TC members should send comments on this specification to the TC's email list. Others should send comments to the TC's public comment list, after subscribing to it by following the instructions at the "Send A Comment" button on the TC's web page at https://www.oasis-open.org/committees/csaf/.
>
> This specification is provided under the Non-Assertion Mode of the OASIS IPR Policy, the mode chosen when the Technical Committee was established. For information on whether any patents have been disclosed that may be essential to implementing this specification, and any offers of patent licensing terms, please refer to the Intellectual Property Rights section of the TC's web page (https://www.oasis-open.org/committees/csaf/ipr.php).
>
> Note that any machine-readable content (Computer Language Definitions) declared Normative for this Work Product is provided in separate plain text files. In the event of a discrepancy between any such plain text file and display content in the Work Product's prose narrative document(s), the content in the separate plain text file prevails.

## Scope CSDPR01 Public Review comment

Received from Christian Keil (DFN-CERT) per email to the public csaf comments mailing list as part of  https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html @santosomar, @tschmidtb51

**Comment by paul-knight** [comment]
I agree with the comment: "correct the links in the section status for the next iteration / progression of the draft".

The OASIS Project Admin staff will not plan to modify the already-published document, but urge the TC Editors to make the appropriate changes in the Markdown source to ensure it is correct for subsequent stages. We will also plan to check future stages of this Work Product to verify the fix.

**Comment by sthagen** [comment]
@paul-knight I will provide the corrections after public review per the next editor revision
