### ISSUE TITLE
Further constraints for semantic version application?

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#358]
# Situation / Comment

> 3.1.11.2 Version Type - Semantic versioning
>
>  The idea of semantic versioning, especially denoting a need to rematch by
increasing the major version is interesting. We are interested to see how
successful this is, regarding the limited success of semantic versioning in
the software world. A strict reading of rule 7 suggests, that the major
version must be increased, if a rematch is necessary. But it doesn't require
that it is only increased if a rematch is necessary. To our reading it would
conform to the rules if the major version is increased for a mere typo. While
an unnecessary rematch is better than a missed rematch, wich is ruled out by
7, this is similar to the situation in the software world where major
versions are sometimes handled quite liberally.

# Proposal (from review comment)

The TC will consider the feedback and analyze the possible contribution from CSAF to constraining the application of semantic versioning.

Comment from @sthagen:
> CSAF allows for a simple integer number representing the version (tagged in the spec as `integer versioning`). In that case the "major" version must change for every update. I can hardly imagine how we can constrain the semantics for those advisories that use a more detailed scheme without excluding integer versioning.

## Scope CSDPR01 Public Review comment

Received from Christian Keil (DFN-CERT) per email to the public csaf comments mailing list as part of  https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html @santosomar, @tschmidtb51

**Comment by santosomar** [comment]
Thank you for the feedback and input. During the TC monthly meeting on Sep 29, 2021, the OASIS Common Security Advisory Framework (CSAF) TC has reviewed your feedback and has voted not to making any changes at this time in CSAF 2.0.
