### ISSUE TITLE
CSDPR01 feedback collector (meta issue)

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#360]
# Feedback from CSD01 Public Review

This issue collects the feedback from the public review of the committee specification draft 01 of CSAF.

The issues were collected per https://github.com/oasis-tcs/csaf/issues?q=is%3Aopen+is%3Aissue+label%3ACSDPR01_feedback

The reason for keeping such a list in a separate issue is to ensure no issue gets lost (due to say a relabel mishap).

## Feedback List of Issues

* #333 
* #334 
* #335 
* #336 
* #337 
* #338 
* #339 
* #340 
* #341 
* #342 
* #343 
* #344 
* #345 
* #346 
* #347 
* #348 
* #349 
* #350 
* #351 
* #352
* (#353)
* #354 
* #355 
* #356 
* #357 
* #358 
* #359 
* #363

Note: One or two issues may be added from a mail of a TC member to the members mailing list publicly accessible at https://lists.oasis-open.org/archives/csaf/202109/msg00000.html

## Issues deemed non-material

TODO

## Issues deemed material

TODO

### Issues within non-standards track documents

TODO

### Issues out of scope for CSAF TC

TODO

**Comment by sthagen** [comment]
This comment shall remain in place until the above issue text is complete and approved by the members of the CSAF TC. After approval of the issue text, this comment will be deleted.

**Comment by tschmidtb51** [comment]
I suggest to close this issue as CS01 was approved in November 2021
