### ISSUE TITLE
Comment Resolution Log CSDPR01 to CS01

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#366]
# Comment Resolution Log

The table summarizes the comments that were received during the 30-day public review of the committee specification draft "[Common Security Advisory Framework Version 2.0](https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html)" and their resolution. Comments came to the csaf-comment and the CSAF TC mailing lists. [The public review did start 14 August 2021 at 00:00 UTC and did end 12 September 2021 at 23:59 UTC](https://www.oasis-open.org/2021/08/13/invitation-to-comment-on-common-security-advisory-framework-v2-0/).

A status of "Completed" in the Disposition column indicates that the editors have implemented the changes on which the TC decided, which are outlined in the Resolution column. It also is a hyperlink to the GitHub commit notice.

The item number is a hyperlink to the e-mail on the csaf-comment or CSAF TC mailing lists.

The following abbreviations are used:

* SH= Stefan Hagen
* TS = Thomas Schmidt

| Item # | Date        | Commenter | Description | Date acknowledged | Resolution | Disposition | 
| ------------- | ------------- |  ------------- |  ------------- |  ------------- |  ------------- |  ------------- |
| [1](https://lists.oasis-open.org/archives/csaf-comment/202108/msg00001.html) | 2021-08-24 | Eliot Lear | [Section 7.1.6: Redirects](https://github.com/oasis-tcs/csaf/issues/342) | 2021-08-25 | Discussed at TC call | No change required |
| [2](https://lists.oasis-open.org/archives/csaf-comment/202108/msg00001.html) | 2021-08-24 | Eliot Lear | [Section 5.1 filename - #343](https://github.com/oasis-tcs/csaf/issues/343) | 2021-08-25 | Discussed at TC call | No change required |
| [3](https://lists.oasis-open.org/archives/csaf-comment/202108/msg00001.html) | 2021-08-24 | Eliot Lear | [Should Section 7 be a part of THIS specification or a separate specification? - #344](https://github.com/oasis-tcs/csaf/issues/344) | 2021-08-25 | Discussed at TC call | No change required |
| [4](https://lists.oasis-open.org/archives/csaf-comment/202108/msg00001.html) | 2021-08-24 | Eliot Lear | [Section 7.1.19: OpenPGP signatures? - #345](https://github.com/oasis-tcs/csaf/issues/345) | 2021-08-26 | Discussed at TC call | No change required |
| [5](https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html) | 2021-09-01 | Christian Keil | [Correct links in status section - these point to OpenC2 instead of CSAF TC #354](https://github.com/oasis-tcs/csaf/issues/354) | 2021-09-08 | Discussed at TC call | [Completed](https://github.com/oasis-tcs/csaf/pull/362/commits/b2c3e6fe7d0e292309cd3253bb3d10ef53eb09d8) |
| [6](https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html) | 2021-09-01 | Christian Keil | [Extend to product identification helpers to mitigate name / vendor changes? #355](https://github.com/oasis-tcs/csaf/issues/355) | 2021-09-08 | Discussed at TC call | No change required |
| [7](https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html) | 2021-09-01 | Christian Keil | [Extend documentation for Notes Type to better guide producers? #356](https://github.com/oasis-tcs/csaf/issues/356) | 2021-09-08 | Discussed at TC call | No change required |
| [8](https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html) | 2021-09-01 | Christian Keil  | [Consider adding Product Status options for vendors to express that there will be no further investigation #357](https://github.com/oasis-tcs/csaf/issues/357) | 2021-09-08 | Discussed at TC call | No change required |
| [9](https://lists.oasis-open.org/archives/csaf-comment/202109/msg00000.html) | 2021-09-01 | Christian Keil | [Further constraints for semantic version application? #358](https://github.com/oasis-tcs/csaf/issues/358) | 2021-09-08 | Discussed at TC call | No change required |
| [10](https://lists.oasis-open.org/archives/csaf/202109/msg00000.html) | 2021-09-08 | Duncan Sparrell | [Terms legacy, end-of-life, and end-of-support #363](https://github.com/oasis-tcs/csaf/issues/363) | 2021-09-28 | Discussed at TC call | No change for version 2.0 required |
| [11](https://lists.oasis-open.org/archives/csaf-comment/202109/msg00001.html) | 2021-09-10 | Patrick Fuller | [Call for assisted input technology to mitigate complexity and support automation #359](https://github.com/oasis-tcs/csaf/issues/359) | 2021-09-11 | Discussed at TC call | No change required |

## Evaluation of Feedback

The editors consider above public comments as well as other more editorial feedback documented in issue [#360](https://github.com/oasis-tcs/csaf/issues/360) and classified/considered per pull request [#362]((https://github.com/oasis-tcs/csaf/issues/362)) as **Non-Material** per OASIS TC process.

A [motion has been issued to the TC mailing list by Stefan Hagen on 2021-10-10](https://lists.oasis-open.org/archives/csaf/202110/msg00000.html) to promote the resulting revised work products to CS01 including  non-material changes only.

To ease verification by anyone and to support the administration a separate release candidate archive containing the 4 standards track work products will be created and linked to this issue as well as noted in the motion to the list.

**Comment by sthagen** [comment]
@santosomar I am currently in consultation with TC administration as there may be a way to shorten the path to the CS01 (my reading of the process was too superficial as eg no public review is usually performed when progressing to CS01) - let us wait with merge until we receive advice, ok?

I set the PR to draft to avoid accidental merge ...

**Comment by OASIS-OP-Admin** [comment]
I agree. Since you are approving a working draft with non-material changes already, might as well fix any that you catch. I will add recommended motion language in a moment.

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51, @OASIS-OP-Admin Looking at the calendar with our next scheduled meeting not much more than a week ahead I intend to 

1. package the typo fixed version up as an RC2 archive with the matching tag and 
2. Create a github „pre-release“ to describe the content and rationale and finally
3. create a motion during the upcoming TC call filling in the placeholders of above example motion.

Thanks to @OASIS-OP-Admin for guiding us through a smooth transition towards Committee Specification level.
