### ISSUE TITLE
Signature file layout definition?

### ISSUE THREAD

**Issue by productcert** [oasis-tcs/csaf#370]
Hi,

The rolie documentation does not specify the format of the [signature files](https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html#7119-requirement-19-signatures). 

Shall the signature file only contain the signature or also the content?

Thanks

**Comment by productcert** [comment]
If you want to keep this issue open for the above mentioned examples keep it open. Otherwise, it could be closed.

**Comment by tschmidtb51** [comment]
@productcert We are tracking the progress of examples now in #374. Therefore, I close the issue.
