### ISSUE TITLE
Starter pack for committee note

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#375]
The [motion](https://lists.oasis-open.org/archives/csaf/202110/msg00008.html) to request a starter pack for the committee note „What‘s New in CSAF 2.0“ carried as it has been https://lists.oasis-open.org/archives/csaf/202110/msg00009.html and the calendar shows we are past the end date 2021-11-03 20:00 UTC.

I was not able to use the [form](https://www-legacy.oasis-open.org/resources/tc-admin-requests/work-product-registration-template-request) and thus submitted a mail to the TC list TC admins monitor.

Request: https://lists.oasis-open.org/archives/csaf/202111/msg00000.html
(Sorry for submitting a clearly unfinished message there, but using that email send form per a tablet is … challenging to me)

Title:  
What‘s New in CSAF 2.0

Editors:
Martin Prpic (mailto:mprpic@redhat.com), Red Hat
Stefan Hagen (stefan@hagen.link), Individual 
Thomas Schmidt (thomas.schmidt@bsi.bund.de), Federal Office for Information Security (BSI) Germany

Format:
markdown

Technical Committee:
OASIS Common Security Advisory Framework (CSAF) TC

@chet-ensign @OASIS-OP-Admin please kindly create such a starter document / pack.
In case some information is missing that you need please ask for it here, on the mailing list or my personal email whichever suits you best.
Thanks,
Stefan Hagen

**Comment by OASIS-OP-Admin** [comment]
Sorry for the difficulties. The ticket is now open at https://issues.oasis-open.org/browse/TCADMIN-4097

**Comment by sthagen** [comment]
Starter pack has been received on the TC mailing list and the initial editor revision will soon be placed for the writing process into this GitHub repo.
