### ISSUE TITLE
product_id or group_id requirement in Remediation

### ISSUE THREAD

**Issue by wrideout** [oasis-tcs/csaf#387]
Currently, there is no requirement that a remediation property of a vulnerability contains product_ids or group_ids if the remediation category is vendor_fix.

**Comment by tschmidtb51** [comment]
Possible duplicate of #383

**Comment by tschmidtb51** [comment]
I suggest to close this in favor of #383 and making this a generic requirement (no only for `vendor_fix`). @wrideout Do you agree?

**Comment by wrideout** [comment]
I agree, and will close this issue.
