### ISSUE TITLE
Add VEX flags

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#390]
The TC should consider to support VEX flags.

**Comment by tschmidtb51** [comment]
Suggestion:
```
          "flags": {
            "title": "List of flags",
            "description": "...",
            "type": "array",
            "minItems": 1,
            "items": {
              "title": "Flag",
              "description": "Contains machine readable flags",
              "type": "object",
              "required": [
                "label",
              ],
              "properties": {
                "label": {
                  "title": "...",
                  "description": "....",
                  "type": "string",
                  "enum": [
                    "component_not_present",
                    "vulnerable_code_not_present",
                    "vulnerable_code_cannot_be_controlled_by_adversary",
                    "vulnerable_code_not_in_execute_path",
                    "vulnerability_mitigations_already_exist"
                  ]
                },
                "date": {
                  "title": "Date of the flag",
                  "description": "...",
                  "type": "string",
                  "format": "date-time"
                },
                "group_ids": {
                  "$ref": "#/$defs/product_groups_t"
                },
                "product_ids": {
                  "$ref": "#/$defs/products_t"
                }
              }
            }
          }
```

**Comment by sthagen** [comment]
That is quite a mouthful, this `vulnerability_mitigations_already_exist` - what about a less redundant `mitigations_already_exist`?

**Comment by sparrell** [comment]
The reason for the 'flags' above is 'status justification' (eg the reason this product is "not_affected" is because "component_not_present"). If the intent is to only use "flags" for 'status justification' then maybe they should be called 'status justification' instead of 'flags'. If, however, the intent is that there may be other uses of this field, then it probably still needs a different name since strictly speaking they are an enum not boolean flags. But if no other name appropriate, I can live with flags.

**Comment by sthagen** [comment]
@sparrell , @tschmidtb51: … or `mitigation_status` Instead of `flags`?

**Comment by sthagen** [comment]
For me the problem with flags (as term for an enumeration) is that the domain is normally a boolean, or a bitfield. In the case of the latter people may start to expect combining the individual flags …
