### ISSUE TITLE
Tag the 2.0 release and the "Committee Specification 01" (cs01) version?

### ISSUE THREAD

**Issue by bernhardreiter** [oasis-tcs/csaf#395]
Withe the cs01 version online at 
  https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html
and the official 2.0 version at
  https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html
(which are the same, but both named "Committee Specification 01")

one or two tags would be useful here, to show, which version is here in the repository,
so issues and other feedback can be geared towards the latest available version or a specific one.

**Comment by sthagen** [comment]
Not so sure about the usefulness of this proposal. Both URLs are official. The latter is a service from OASiS to offer early on a stable latest place. There is no difference until … there is a promotion, when cs01 will drift into oblivion and some other happy twins will be present, like a CS02 and that latest document, or an OS …

**Comment by bernhardreiter** [comment]
@sthagen the proposal is to clarify what corresponds to the version here in the repository and the OASiS official URLs. If both are the same: add two tags and it is clear.  So far there are only draft tags.

The naming problem confusion on https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html is probably an OASiS matter, I've mentioned it to show that resolving the confusion is adding value. (The naming problem is that if you go to https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html it says that "this stage is cs01" and the "next stage is 2.0", but the url marks this as "2.0" so the reader cannot be sure that both documents are the same and cannot be sure that the page is the wanted one, as it denies itself recognition. >;) If here in the repos there are two tags that both point to one source code version, then at leat here, for the place to comment, it is clear enough.)

**Comment by sthagen** [comment]
That is why we have the releases e.g. for current latest and CS01 that is https://github.com/oasis-tcs/csaf/releases/tag/cs-01-20211027-rc2 which documents the tag as cs-01-20211027-rc2 - any changes from TC admins during publication may or may not have occurred and may distinguish the effective version from the repo originating source. 

We may flow the published version back into the editor revisions and the tag with CS01 but until then the release candidate 02 is the closest we have.

I may have developed a standardization practises blindspot, but I do not see the problem of the latest vs. CS01.

**Comment by bernhardreiter** [comment]
> We may flow the published version back into the editor revisions and the tag with CS01 but until then the release candidate 02 is the closest we have.

Okay, just wondering. To me it is unclear if the source in here should be equivalent to cs01 or 2.0 or not.

This is just from the perception of a reader and commenter, I'm looking for the best way to comment and potentially help to improve the next revision of the CSAF 2.0 standard. A citation or even a merge-request would require to know which the latest version is (may it be 2.0 or something else).

**Comment by sthagen** [comment]
Both with a should, both with a shall (after a PR from the effective version), 2.0 and e.g. CS02 when we did a CS02

**Comment by sthagen** [comment]
@bernhardreiter I just did that:
> We may flow the published version back into the editor revisions and the tag with CS01 but until then the release candidate 02 is the closest we have.

**Comment by bernhardreiter** [comment]
Mentioned on csaf-comment today: https://groups.oasis-open.org/discussion/other-suggestions-partly-already-handled-395-396-397-398-469-470-477-508
