### ISSUE TITLE
Clarify handling of CVSS conversion

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#423]
There are a few things unclear when converting CVSS from CVRF to CSAF. We should clarify:
1. What should happen, when the `product_status` element is not given? => suggestion: error in conversion
2. What should happen, if the CVSS vector was not given? => suggestion: error in conversion
3. How to reliable determine CVSS 3.x versions?

**Comment by tschmidtb51** [comment]
@sthagen: Does that sound reasonable?

**Comment by sthagen** [comment]
> @sthagen: Does that sound reasonable?

I guess implementers will be able to use these steps for the processing. So, yes.
