### ISSUE TITLE
Clarify conversion of `Realm` and `Resource`

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#425]
The [XML schema](https://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/prod.xsd) defines `Realm` and `Resource` as possible  `Type` for a `Branch` - the [specification](http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-cs01.html#_Toc493508797) does not. We need to clarify, what to do, if such values occur.

Suggestion: Convert them into a `product_name` and add a warning that those types do not exist in CSAF.

@sthagen: Do you agree?

**Comment by sthagen** [comment]
@tschmidtb51 Yes, I agree to convert and warn (for any conforming CVRF to CSAV converter)
