### ISSUE TITLE
Clarify filename computation

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#441]
Currently, it seems to be unclear whether consecutive characters which should be replaced by an `_` get one or multiple `_`.

Example: `Hans Peter_Hase 010-10==?/1,+-`

1. Multiple: `hans_peter_hase_010-10____1_+-`
2. Single: `hans_peter_hase_010-10_1_+-`

Personally, I prefer option 2.

@sthagen: Thoughts?

**Comment by sthagen** [comment]
`tr -s '_'` is nice, but a shape changing transform (for converters :wink:) may risk collisions that did not exiust in the CVRF files ...

**Comment by tschmidtb51** [comment]
> `tr -s '_'` is nice, but a shape changing transform (for converters wink) may risk collisions that did not exist in the source CVRF files ...

So you would go with 1?
