### ISSUE TITLE
Add vulnerability to terminology

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#453]
In CVRF CSAF 1.2, we defined vulnerability according to ISO 29147. Currently, we do not have any definition in the document. Therefore, I suggest to either use that from ISO 29174 (which is currently not available to me; @zmanion (or anyone) are you able to provide that?) 

or use the one from the [The CERT Guide to Coordinated Vulnerability Disclosure](https://vuls.cert.org/confluence/display/CVD/1.2.+CVD+Context+and+Terminology+Notes):

> A vulnerability is a set of conditions or behaviors that allows the violation of an explicit or implicit security policy.

Thoughts?

CC: @tolim, @mprpic, @santosomar, @wrideout

**Comment by sthagen** [comment]
The ISO definitionfrom ISO/IEC 29147-2018 is (cf. https://www.iso.org/obp/ui/#iso:std:iso-iec:29147:ed-2:v1:en section 3 "Terms and definitions"):
>3.1
>vulnerability
>functional behaviour of a product or service that violates an implicit or explicit security policy
>
>Note 1 to entry: [ISO/IEC 27002:2013, 12.6.1](https://www.iso.org/obp/ui/#iso:std:iso-iec:27002:ed-2:en:clause:12.6.1)[[1]>(https://www.iso.org/obp/ui/#iso:std:iso-iec:29147:ed-2:v1:en:ref:3)] uses the term “technical vulnerability” to distinguish >between the more general risk-based concept of vulnerability and the term used in this document.

So I suggest to re-add that ref and use in our glossary:
> **vulnerability**: functional behavior of a product or service that violates an implicit or explicit security policy (conforming to ISO/IEC 29147)

... and we are clean again (note the different spelling of behavior we SHALL use 😄 ).

As that glossary term is short, sweet, and surprisingly free available we should really use it.

**Comment by tschmidtb51** [comment]
Agreed. See #456.
