### ISSUE TITLE
Remediation artifacts

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#47]
The field "type" in items of the array "remediations" should  be required as stated in the specification of CVRF 1.2 (see https://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-cs01.html#_Toc493508946).

**Comment by santosomar** [comment]
This is a great catch! Yes, it should be required, as per the previous 1.2 release.
