### ISSUE TITLE
Disallow list_on_CSAF_aggregators = false, if mirror_on_CSAF_aggregators == true

### ISSUE THREAD

**Issue by bernhardreiter** [oasis-tcs/csaf#477]
In 7.2 it could be clarified that `mirror_on_CSAF_aggregators = true` forces `list_on_CSAF_aggregators = true` as it probably does not make sense to disallow listing if someone can mirror. ;)

**Comment by tschmidtb51** [comment]
This was already addressed in #473 - but in a slightly different way than you suggested.

**Comment by bernhardreiter** [comment]
Thanks for clarifying!

**Comment by bernhardreiter** [comment]
Mentioned on csaf-comment today: https://groups.oasis-open.org/discussion/other-suggestions-partly-already-handled-395-396-397-398-469-470-477-508
