### ISSUE TITLE
Pattern for csaf ID incorrect?

### ISSUE THREAD

**Issue by Id3aFly** [oasis-tcs/csaf#478]
**Current situation:** 
When using the pattern `^[\\S](.*[\\S])?$` from https://github.com/oasis-tcs/csaf/blob/98992c1a4ec80e5030daf1573f33512a98deba9e/csaf_2.0/json_schema/csaf_json_schema.json#L793 which is specifying the id of an advisory, I am not able to match the provided examples https://github.com/oasis-tcs/csaf/blob/98992c1a4ec80e5030daf1573f33512a98deba9e/csaf_2.0/json_schema/csaf_json_schema.json#L795-L798

I am using python with the re module.  

**Solution:**
In my opinion the problem is that `[\\S]` evaluates to the set `{\,S}`. Actually it should be `[\S]` what matches a not whitespace character.
`^[\S](.*[\S])?$` also matches the provided examples.

**Comment by sthagen** [comment]
In python "it" (the funny value in all regex entries of a JSON schema) should be read (here) as: `r'^[\S](.*[\S])?$'` the schema/js people need the escape because they do not have "raw" stings.

**Comment by Id3aFly** [comment]
Thanks for the explanation, thank you.

**Comment by Id3aFly** [comment]
I found the problem in my code: I was using a raw string, r'' instead of the non-raw version.
`re.match(r'^[\\S](.*[\\S])?$', "Advisory-123")` fails
`re.match('^[\\S](.*[\\S])?$', "Advisory-123")` works

**Comment by tschmidtb51** [comment]
I also verified that the pattern with a little script in js:

```javascript
const fs = require('fs')

const args = process.argv.slice(2);
const obj = JSON.parse(fs.readFileSync(args[0], 'utf8'))

const pattern = obj.properties.document.properties.tracking.properties.id.pattern
const r = new RegExp(pattern)

console.log('Current regex to test:', '\t', pattern)

var example = obj.properties.document.properties.tracking.properties.id.examples

example.push(" Example", "\tJust tab", "Space here at end    ")

example.forEach(element => {
    if (element.length > 0) {
        const result = (r.exec(element) != null)  
        console.log(result, '\t"'+element+'"')
    }
});
```

That can be called with `node script-name json-schema`. It results in:

```
Current regex to test: 	 ^[\S](.*[\S])?$
true 	"Example Company - 2019-YH3234"
true 	"RHBA-2019:0024"
true 	"cisco-sa-20190513-secureboot"
false 	" Example"
false 	"	Just tab"
false 	"Space here at end    "
```
