### ISSUE TITLE
Motion to publish current editor draft as CSD 02

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#479]
In release https://github.com/oasis-tcs/csaf/releases/tag/csd-02-20220219-rc1 we provide all artifacts needed and a link to the email on the TC maing list that moves to publish the current editor draft as CSD 02.

**Comment by santosomar** [comment]
The motion to approve CSAF Version 2.0 Working Draft as Committee Specification Draft 02 has passed as stated: 

 - motion: https://lists.oasis-open.org/archives/csaf/202203/msg00000.html 
- second: https://lists.oasis-open.org/archives/csaf/202203/msg00002.html

Congratulations! We will now proceed with the next steps as stated in the TC process at https://www.oasis-open.org/policies-guidelines/tc-process-2017-05-26/#committeeSpec
