### ISSUE TITLE
Warn about non-standard keywords

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#503]
We should clarify that automation and scalability heavily depend on the usage of certain keywords... Maybe as test (optional) or editorial note?

**Comment by tschmidtb51** [comment]
@sthagen I saw you confused emoji - please have a look at #505 and #506.

**Comment by sthagen** [comment]
> @sthagen I saw you confused emoji - please have a look at #505 and #506.

.. so your eyes are better than mine - sorry confusion was not my sentiment; I always perceived my hands and fingers as being small …
