### ISSUE TITLE
Remediations are confusing

### ISSUE THREAD

**Issue by tom1972-de** [oasis-tcs/csaf#512]
Valid values of remediations are according to "3.2.3.11.1 Vulnerabilities Property"

-     mitigation
-     no_fix_planned
-     none_available
-     vendor_fix
-     workaround

This mixes "available remediations" and "plans for the future".

"Available remediations" are:

-     mitigation
-     workaround
-     vendor_fix

    

"no_fix_planned" is not a "remediation" but a plan for the future. Also it would only work with "mitigation" and "workaround". "no_fix_planned" and "vendor_fix" exclude each other.

I recommend to explain this in the document.

Regarding "none_available": This term is unclear. It could mean "no_remediation_avalilable". But later in the text is is explained that it is "no_vendor_fix_available".

"no_vendor_fix_available" does not make sense as it can easily be expressed by just not including a "vendor_fix".
"no_remeditation_available" could make sense as the remediation_section could still have "no_fix_planned" as an entry.

**Comment by tschmidtb51** [comment]
@tom1972-de / @tlimmer: Please have a look at #540. Does that clarify the confusion?

**Comment by tschmidtb51** [comment]
It the wording ok?

**Comment by tom1972-de** [comment]
> It the wording ok?

For me it is fine!
