### ISSUE TITLE
Add missing reference [VEX-Just]

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#517]
# Situation

The Reference to `[VEX-Just]` is listed in [1.4 Informative References](https://docs.oasis-open.org/csaf/csaf/v2.0/csd02/csaf-v2.0-csd02.html#14-informative-references) as `TBA`.

# Proposal

Either remove the reference or link to a draft version of the document.

Maybe, we should also improve the name of the reference...

**Comment by tschmidtb51** [comment]
Flagging @sparrell, @allan-ntia for attention.

**Comment by sthagen** [comment]
I think the name is OK (VEX and VEX-Just side by side.
