### ISSUE TITLE
Reference security.txt as RFC9116

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#522]
# Situation

It looks like the security.txt got a RFC number assigned. If that is stable, we should refer to that as well.

# Proposal

Add a reference to RFC9116.

**Comment by tschmidtb51** [comment]
@sthagen Could you please double check on the RFC status?

**Comment by sthagen** [comment]
Published: https://www.rfc-editor.org/rfc/rfc9116 I think about two days ago (depending on the timezone one is living in): https://datatracker.ietf.org/doc/rfc9116/
