### ISSUE TITLE
Entity vs Person

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#544]
Currently, the metadata of `$defs/acknowledgments_t[]/names` states: 
>          "title": "List of acknowledged names",
>          "description": "Contains the names of entities being recognized.",

And, the metadata of `$defs/acknowledgments_t[]/names[]` states: 
>            "title": "Name of entity being recognized",
>            "description": "Contains the name of a single person.",

However, as we talk about persons (according to the last one) we should probably change entity to person. Or can that be used synonymous in English?

Flagging @mprpic, @santosomar  as native speakers...

**Comment by santosomar** [comment]
In some cases, the vulnerability acknowledgment is only done to an organization vs a person. It's very seldom that a researcher does not want their name there, but instead the organization. However, it happens from time to time. Entity may be ok.

**Comment by tschmidtb51** [comment]
When only the organization should be listed than this should be done through the `organization` field...
