### ISSUE TITLE
parts vs partial

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#545]
Model number, serial number, sku contain a description that could be misleading:
>                "description": "Contains a part, or a full model number of the component to identify.",
>                "description": "Contains a part, or a full serial number of the component to identify.",
>                "description": "Contains a part, or a full stock keeping unit (SKU) which is used in the ordering process to identify the component.",

IMHO it is clear from the prose, that we want to have either full (model|serial) numbers or parts of (model|serial) numbers in there.

The same applies for the parent elements:
>               "description": "Contains a list of parts, or full model numbers.",
>               "description": "Contains a list of parts, or full serial numbers.",
>               "description": "Contains a list of parts, or full stock keeping units.",

Maybe, we should use then "partial" or "stripped-down" or "condensed" instead? Or switch "parts" and "full"?

Flagging @mprpic, @santosomar as native speakers...

**Comment by santosomar** [comment]
Perhaps, "abbreviated (partial) vs. full (complete)"?
