### ISSUE TITLE
Clarification of validation 6.1.31

### ISSUE THREAD

**Issue by rselph-tibco** [oasis-tcs/csaf#547]
I'd like to propose the following for validation 6.1.31 (Version Range in Product Version):

```
> To implement this test it is deemed sufficient that, when converted to lower case, the value of `name` does not contain any of the following strings:
>
> ```
>   <
>   >
>   all
>   versions
>   later
>   prior
>   after
>   before
> ```
```

The differences are:
* Remove `<=` and `>=`, as these are redundant with `<` and `>`
* Add `after` and `before` as strings to detect, as these are commonly used for expressing ranges
* Clarify that the match should be case insensitive
* Separate `all` and `versions`, since these could  conceivably be used independently

**Comment by tschmidtb51** [comment]
Lets discuss that in tomorrows meeting.
