### ISSUE TITLE
Group_id and groups type

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#57]
The value of "group_id" is used multiple times. However, it is semantically not the same as a "product_id". Following the DRY principle and to prepare for a unique product identifier where also the definition of these types will differ the corresponding definitions should be extracted to types.

**Comment by santosomar** [comment]
During the June 24, 2020 monthly meeting, it was suggested and discussed to rename to product_group_id_t to make relationship to products explicit, as stated by @tolim above. The TC decided that this is the right approached (i.e., rename to product_group_id_t).
