### ISSUE TITLE
Update CSAF to use TLP 2.0

### ISSUE THREAD

**Issue by ddillard** [oasis-tcs/csaf#591]
I'm not sure of all of the differences between TLP 1.0 and 2.0, but the one that immediately jumps out at me when reading the CSAF 2.0 spec and the TLP 2.0 spec is that TLP 2.0 has added TLP:AMBER+STRICT.  I also see that TLP:CLEAR replaces TLP:WHITE.  

TLP:AMBER+STRICT is the kind of thing I believe many commercial orgs would want to use instead of TPL:AMBER (my company certainly would).

**Comment by tschmidtb51** [comment]
Except for the TLP:AMBER+STRICT, you can also use TLP v2 with the current CSAF 2.0. Nevertheless, the change to TLP v2 is on our roadmap for CSAF 2.1.

**Comment by tschmidtb51** [comment]
> Except for the TLP:AMBER+STRICT, you can also use TLP v2 with the current CSAF 2.0. Nevertheless, the change to TLP v2 is on our roadmap for CSAF 2.1.

This comment might have been misleading. Therefore, I would like to clarify: CSAF 2.0 does not allow the enum values `CLEAR` or `AMBER+STRICT` as those are not in the schema. However, as the mapping table is as follows:
| TLPv2 | TLPv1 |
|--------|--------|
| `TLP:CLEAR` | `TLP:WHITE` |
| `TLP:GREEN` | `TLP:GREEN`  |
| `TLP:AMBER` | `TLP:AMBER` |
| `TLP:AMBER+STRICT` | _not present_ |
| `TLP:RED` | `TLP:RED` | 

one can display (e.g. in a human readable advisory) TLPv2 labels while using TLPv1 keywords (in the CSAF file). (Except for `TLP:AMBER+STRICT` but that has been mentioned before.)
