### ISSUE TITLE
Feature request: Add source (reference) to CVSS

### ISSUE THREAD

**Issue by jaccoNCSCNL** [oasis-tcs/csaf#624]
As a national CERT we often bundle multiple advisories into one. This also means that we sometimes have conflicting CVSS scores from different sources for the same vulnerability.
We think that it would make sense to add an optional source (or reference) to a CVSS score which would indicate who made this score.

**Comment by tschmidtb51** [comment]
Thank you for the suggestion. The TC will discuss the suggestion.

**Comment by sthagen** [comment]
During the 2023-09-27 meeting of the TC the members agreed to implement the feature in CSAF v2.1.

**Comment by tschmidtb51** [comment]
@jaccoNCSCNL To follow the OASIS process, please also announced the request on the [comment mailing list](https://groups.oasis-open.org/communities/community-home?communitykey=3720cda2-3056-4183-a759-018f5aa7b5f2). A simple email pointing to the issue should be sufficient.

**Comment by jaccoNCSCNL** [comment]
This has been announced at https://groups.oasis-open.org/discussion/feature-request-add-source-reference-to-cvss
