### ISSUE TITLE
Appendix C: Raise file size softlimit

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#626]
The practice has shown that the current file size soft limit, given through [Appendix C.1](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#c1-file-size) does not meet the needs in practice. At least Red Hat is generating files that are bigger than 15 MB.
Therefore, I suggest to raise the file size limit to 50 MB.

**Comment by sthagen** [comment]
During the 2023-09-27 meeting of the TC the members approved to raise the limit to 50 Megabytes as proposed in CSAF v2.1.
