### ISSUE TITLE
Publish article to document CSAF with CDN 

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#640]
A CDN provider suggested to publish a short article / best practice / guidance document on what CSAF providers need to think about when they use a CDN for distribution. Here are the suggestions:

- **Activate caching:** Most files are more or less static - activate caching to minimize risk for (D)DoS.
- **Include path exemption:** The path
   ```
   .well-known/csaf/
   ```
   and potentially `.well-known/security.txt` need to be accessible for all HTTP-clients (also those that are usually detected as bots). 
   _Note: We might be able to be more specific as our filename restrictions aid in predictive filenames._
- **Flush cache when updating files:** When new files are written or old files updated, the cache must be updated. This can be done through the API the CDN provides. Instead of flushing the whole cache (easy way), a more precise way should be suggested as we known which files have to be updated (according to the distribution method).

Thoughts?

**Comment by mprpic** [comment]
It might be also worth mentioning that any rate limiting enforced by the CDN should account for the number of files in the entire data set. If someone attempts downloading all files in a CSAF data set, they should be able to do so without seeing any 429 errors with a reasonable level of concurrency (say 10 threads pulling the files one by one).

I also wonder if any rate limiting could be advertised upfront in the provider-metadata.json file in some standardized way, for example X number of requests per second.

**Comment by santosomar** [comment]
Discussed with the TC on the August 30th, 2023 meeting. The decision was to potentially publish generic guidance to the community in the https://csaf.io website under https://csaf.io/cdn 

When a CSAF publisher or provider/trusted provider uses Content Delivery Network (CDN) solutions different issues can arise that may restrict or interfere with access to the `.well-known/csaf` path. The aforementioned suggestions by @tschmidtb51 can serve as generic guidance to CSAF publishers, providers, and trusted providers. A draft will be shared with the TC prior to publication.
