### ISSUE TITLE
Warning/Error for signature expirations

### ISSUE THREAD

**Issue by ctron** [oasis-tcs/csaf#678]
When documents are signed with a key, that key/certificate may expire, making the validation of such signatures problematic.

I believe there should be a grace period in the specification which requires that there is "enough" time left. And while one can argue about the exact number, I think it would make sense to have two requirements in the spec:

* Signatures MUST be valid for 30 more days
* Signatures SHOULD be valid for 90 more days

**Comment by santosomar** [comment]
Comment from the TC (Denny) : "Signatures MUST be valid for at least 30"

**Comment by santosomar** [comment]
As discussed in the CSAF TC monthly meeting on 2024-02-28, this will be added to the guidance documentation for CSAF 2.0.

**Comment by tschmidtb51** [comment]
As discussed in the CSAF TC monthly meeting on 2024-04-24, the wording from #724 will be added to CSAF 2.1.

**Comment by tschmidtb51** [comment]
@ctron  The [comments mailing](https://groups.oasis-open.org/communities/community-home?communitykey=3720cda2-3056-4183-a759-018f5aa7b5f2) list is now back online. Please formally announce your suggestion there, e.g. through "Please see our suggest in Github Issue XYZ (https://github.com/oasis-tcs/csaf/issues/XYZ)."

Thank you!

**Comment by tschmidtb51** [comment]
The issue was suggested on the mailing list: https://groups.oasis-open.org/discussion/warningerror-for-signature-expirations

**Comment by tschmidtb51** [comment]
The issue was resolved with #723 and #724
