### ISSUE TITLE
Add Trivy to the list of CSAF Open Source Tools

### ISSUE THREAD

**Issue by mpermar** [oasis-tcs/csaf#685]
Trivy is now able to process CSAF VEX files and use that for filtering false positives out of scanning reports. See following links for references:

https://twitter.com/AquaTrivy/status/1753059175217664066
https://twitter.com/AquaTrivy/status/1753059168439693680

It would be great adding them to the list of [Open Source Tools](https://oasis-open.github.io/csaf-documentation/tools). I was going to submit a PR myself but I cannot find that web page source code. Can someone point me to its source?

**Comment by tschmidtb51** [comment]
Sure. The code is at https://github.com/oasis-open/csaf-documentation/blob/master/tools.html. There was also already an issue to that, feel free to point your PR to https://github.com/oasis-open/csaf-documentation/issues/50

**Comment by tschmidtb51** [comment]
I added a PR https://github.com/oasis-open/csaf-documentation/pull/51 but I'm not sure, whether it is complete...

**Comment by mpermar** [comment]
Hey, yes, that's just perfect. Thanks!

**Comment by tschmidtb51** [comment]
The tool has been added to the CSAF tool list.
