### ISSUE TITLE
CLA requirement

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#695]
I came across a [repo of an OASIS Open Project which has a section](https://github.com/opencybersecurityalliance/casp?tab=readme-ov-file#cla--non-assert-signatures-required):

> # CLA & Non-assert signatures required
>
> All technical contributions must be covered by a Contributor's License Agreement. This requirement allows our work to advance through OASIS standards development stages and potentially be submitted to de jure organizations such as ISO. You will get a prompt to sign this document when you submit your first pull request to a project repository, or you can sign [here](https://www.oasis-open.org/open-projects/cla/oasis-open-projects-individual-contributor-license-agreement-i-cla/). If you are contributing on behalf of your employer, you must also sign the ECLA [here](https://www.oasis-open.org/open-projects/cla/entity-cla-20210630/).

Do we need the same thing for this repo? If we don't have to, should we have it (better save than sorry)?

**Comment by sthagen** [comment]
@chet-ensign thanks a lot for the confirmation - closing the question / issue as resolved.
