### ISSUE TITLE
Add "Preconditions" item

### ISSUE THREAD

**Issue by boschpsirt** [oasis-tcs/csaf#706]
There are different note categories in the Vulnerabilities -> Vulnerability Notes section. We noticed that the “Preconditions” item is missing. Preconditions can be local privileges, executions rights, physical access, etc. 

Of course you can solve this with the “Details” item, but we would highlight this as a separate category

**Comment by tschmidtb51** [comment]
I see a couple of options here:
1. Go the machine-readable way and present options for the `preconditions` (Then, we need to discuss which ones.)
2. Specify "Precoditions" a fixed `title` for a vulnerability note (similar to `CVE description`)
3. Add a human-readable field (probably the least favorable)

**Comment by tschmidtb51** [comment]
@boschpsirt Please also formally notify about the suggestion by writing to the csaf-comment mailing list (as soon as its back online).

**Comment by tschmidtb51** [comment]
As discussed in today's TC meeting (2024-03-27):

@boschpsirt The TC tends to incorporate solution 2 into the standard. Before I set the motion to do so, any final comments?

**Comment by boschpsirt** [comment]
@tschmidtb51  we also prefer solution 2. Go for it :)

**Comment by santosomar** [comment]
The motion to accept solution 2 as suggested in #706 https://github.com/oasis-tcs/csaf/issues/706 and include it in CSAF 2.1 has passed. No objection was received and the motion automatically passed on 2024-04-04 15:00 UTC.

This was announced at: https://groups.oasis-open.org/discussion/motion-for-706

**Comment by santosomar** [comment]
This motion has automatically passed on 2024-05-01 23:00 UTC.

https://groups.oasis-open.org/discussion/motion-for-724

**Comment by tschmidtb51** [comment]
@boschpsirt: The [comments mailing](https://groups.oasis-open.org/communities/community-home?communitykey=3720cda2-3056-4183-a759-018f5aa7b5f2) list is now back online. Please formally announce your suggestion there, e.g. through "Please see our suggest in Github Issue XYZ (https://github.com/oasis-tcs/csaf/issues/XYZ)."

Thank you!

**Comment by tschmidtb51** [comment]
The issue was announced on the mailing list: https://groups.oasis-open.org/discussion/github-issue-706
