### ISSUE TITLE
Language type regular expression

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#71]
#67 was reviewed and approved by TC during the June 24, 2020 monthly meeting. @santosomar summarizes the discussions and call for suggestions about the pattern:

> TC members are encouraged to suggest any additional edits to the pattern/string "pattern": "^[a-zA-Z]{2,3}(-.+)?$" . Additional information about the convention (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) and other items are documented in the associated issue and were also discussed during the June 24, 2020 monthly meeting.

This is an issue to track and discuss these suggestions.

**Comment by tschmidtb51** [comment]
The original issue was #66.

**Comment by sthagen** [comment]
This issue is about correcting the current regex and aligning with BCP 47

**Comment by tschmidtb51** [comment]
Figure 1 on [BCP47](https://www.ietf.org/rfc/bcp/bcp47.txt) explains the ABNF.

**Comment by tschmidtb51** [comment]
Here is the regex: `^(([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})(-[A-Za-z]{4})?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-[A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+)*(-x(-[A-Za-z0-9]{1,8})+)?|x(-[A-Za-z0-9]{1,8})+|i-default|i-mingo)$`

And the way to it:
```
Language-Tag = langtag | privateuse | grandfathered

langtag = language(-script)?(-region)?(-variant)*(-extension)*(-privateuse)?

language = ([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})
script = [A-Za-z]{4}
region = ([A-Za-z]{2}|[0-9]{3})
variant = ([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3})
extension = [A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+

privateuse = x(-[A-Za-z0-9]{1,8})+
grandfathered = i-default|i-mingo
```

**Comment by sthagen** [comment]
Maybe we should have some tests to guard our `way from ABNF to regex`?

**Comment by tschmidtb51** [comment]
@sthagen Have you tried `^((([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})(-[A-Za-z]{4})?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-[A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+)*(-x(-[A-Za-z0-9]{1,8})+)?)|(x(-[A-Za-z0-9]{1,8})+)|(i-default)|(i-mingo))$`

**Comment by sthagen** [comment]
ABNF is case insensitive. As convention people use either single quotes or scan codes to indicate special case. Using only lower case is a recommendation but not mandatory (my reading and what comes from `the other third party validator` used  as report).

the regex I tried is at https://github.com/sthagen/language-tag-abnf-regex/blob/default/grammar/regular-expression/language-tag.regex - I can try
`^((([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})(-[A-Za-z]{4})?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-[A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+)*(-x(-[A-Za-z0-9]{1,8})+)?)|(x(-[A-Za-z0-9]{1,8})+)|(i-default)|(i-mingo))$ `
tomorrow.

**Comment by tschmidtb51** [comment]
I would love to stick to case sensitivity (at least for the grandfathered and privateuse parts) as people will check that against the IANA registry and it makes the regex more readable...

Anyway, here is the updated version:
`^(([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})(-[A-Za-z]{4})?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-[A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+)*(-[Xx](-[A-Za-z0-9]{1,8})+)?|[Xx](-[A-Za-z0-9]{1,8})+|[Ii]-[Dd][Ee][Ff][Aa][Uu][Ll][Tt]|[Ii]-[Mm][Ii][Nn][Gg][Oo])$`

**Comment by sthagen** [comment]
I do not think, that case matters for validation. It may help users or they may be used to it, but the spec is quite clear on that:
```
2.1.1.  Formatting of Language Tags

   At all times, language tags and their subtags, including private use
   and extensions, are to be treated as case insensitive: there exist
   conventions for the capitalization of some of the subtags, but these
   MUST NOT be taken to carry meaning.

   Thus, the tag "mn-Cyrl-MN" is not distinct from "MN-cYRL-mn" or "mN-
   cYrL-Mn" (or any other combination), and each of these variations
   conveys the same meaning: Mongolian written in the Cyrillic script as
   used in Mongolia.

   The ABNF syntax also does not distinguish between upper- and
   lowercase: the uppercase US-ASCII letters in the range 'A' through
   'Z' are always considered equivalent and mapped directly to their US-
   ASCII lowercase equivalents in the range 'a' through 'z'.  So the tag
   "I-AMI" is considered equivalent to that value "i-ami" in the
   'irregular' production.
```

As the ABNF and the above prose suggest (BCP47 part, Phillips & Davis,  Best Current Practice [Pages 5/6], RFC 5646, Language Tags,  September 2009)

**Comment by sthagen** [comment]
The ad hoc test repo has a JSON schema compatible REGEX that matches all tags from random corpus (based on ABNF of BCP 47):
```
^(([A-Za-z]{2,3}(-[A-Za-z]{3}(-[A-Za-z]{3}){0,2})?|[A-Za-z]{4,8})(-[A-Za-z]{4})?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-[A-WY-Za-wy-z0-9](-[A-Za-z0-9]{2,8})+)*(-[xX](-[A-Za-z0-9]{1,8})+)?|[xX](-[A-Za-z0-9]{1,8})+|[eE][nN]-[gG][bB]-[oO][eE][dD]|[iI]-[aA][mM][iI]|[iI]-[bB][nN][nN]|[iI]-[dD][eE][fF][aA][uU][lL][tT]|[iI]-[eE][nN][oO][cC][hH][iI][aA][nN]|[iI]-[hH][aA][kK]|[iI]-[kK][lL][iI][nN][gG][oO][nN]|[iI]-[lL][uU][xX]|[iI]-[mM][iI][nN][gG][oO]|[iI]-[nN][aA][vV][aA][jJ][oO]|[iI]-[pP][wW][nN]|[iI]-[tT][aA][oO]|[iI]-[tT][aA][yY]|[iI]-[tT][sS][uU]|[sS][gG][nN]-[bB][eE]-[fF][rR]|[sS][gG][nN]-[bB][eE]-[nN][lL]|[sS][gG][nN]-[cC][hH]-[dD][eE])$
```

**Comment by tschmidtb51** [comment]
> I do not think, that case matters for validation. It may help users or they may be used to it, but the spec is quite clear on that:

You're right. Thanks for pointing that out. I changed the remark about that in 86da018.
