### ISSUE TITLE
Add optional test: `/document/tracking/id` not in  `/document/title`

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#717]
Currently, some publishing parties include the `/document/tracking/id` in the `/document/title`. We should add an optional test (and quick fix / conversion rule) that checks on this.

Reasoning:
The data should not be duplicated - especially as this makes it harder to fulfill the requirements for a CSAF modifier. Also, it consumes space in tools that present the data to users that could be filled with better information.

**Comment by tschmidtb51** [comment]
Note: This does not affect currently existing CSAF documents. (Nevertheless, an optional conversion rule "remove `/document/tracking/id` from `/document/title` can be added in #673). Moreover, it is an optional test. This implies, documents that fail the test are still valid.

**Comment by santosomar** [comment]
The motion related to this issue has automatically passed on 2024-05-01 23:00 UTC.
https://groups.oasis-open.org/discussion/motion-for-717
