### ISSUE TITLE
Set `TLP:CLEAR` as default 

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#721]
We are expecting that most CSAF documents will be freely accessible. So, I guess we should make `TLP:CLEAR` a default value in the schema.

**Comment by santosomar** [comment]
A motion will be put in place via email after the CSAF TC meeting on April 24, 2024.

**Comment by tschmidtb51** [comment]
Note: Setting the default value in the schema does not change the ability to publish CSAF documents with other TLP labels. It also does not change existing CSAF documents with a given TLP label. However, it will provide a suggested default for anyone writing CSAF documents (where as the majority of those will be public.) This enables better adoption as a newcomer does not have to figure out what TLP is, but can use the default value.

**Comment by santosomar** [comment]
The motion has passed. 
https://groups.oasis-open.org/discussion/motion-for-721
