### ISSUE TITLE
Clarify relation of  `search` and `filter`

### ISSUE THREAD

**Issue by bernhardreiter** [oasis-tcs/csaf#730]
A CSAF content management system can be called one if it
provides at least the following management functions (in CSAF 2.0 and current 2.1 draft):

https://github.com/oasis-tcs/csaf/blob/3df3076f1288154889a2e389eec4a3d539ea4844/csaf_2.1/prose/edit/src/conformance.md?plain=1#L211-L214

(same for the CSAF management system:)

https://github.com/oasis-tcs/csaf/blob/3df3076f1288154889a2e389eec4a3d539ea4844/csaf_2.1/prose/edit/src/conformance.md?plain=1#L382-L385

As those two are the only mentions of `filter`, it not entirely clear what it means and should be clarified.
In a personal conversion with @tschmidtb51 I've learned that "filter" aims to refining the results of an initial _search_ further.  

However this is not yet clear from the document itself. To _filter_ all possible entries in a system via a _search_ term would also make sense to me. Or to _search_ for something in a result set that has already been filtered down.

If it is the case that further filtering is meant, maybe changing the requirement to something like this makes it more clear:
  ` * allows to apply additional filters on intermediate search results on all properties which it is required to search for`

**Comment by bernhardreiter** [comment]
@tschmidtb51 thanks for the hint, I've found how to subscribe at:
https://www.oasis-open.org/committees/comments/index.php?wg_abbrev=csaf

**Comment by tschmidtb51** [comment]
The issue was brought up un the mailing list: https://groups.oasis-open.org/discussion/suggestion-clarify-search-and-filter-730
