### ISSUE TITLE
Add optional test: Warn if vulnerability mapping is not in state `allowed`

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#743]
The CWE specification has several status for the usage of a CWE-ID for Vulnerability Mapping:
- "Allowed" 
- "Allowed-with-Review"
- "Discouraged"
- "Prohibited" (covered by 6.1.11)

We should provide a test that warns, if somebody uses a CWE with another state than "allowed" to aid in improving the data quality.

**Comment by santosomar** [comment]
The motion to add the optional test as suggested in https://github.com/oasis-tcs/csaf/issues/743 and include it into CSAF 2.1, has passed. It automatically carried on 2024-06-05 23:00 UTC.
https://groups.oasis-open.org/discussion/motion-for-743
