### ISSUE TITLE
New Product_status: under_investigation

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#77]
Sometimes a vendor is unable to tell which devices are affected but wants to inform that he is investigating the issue. This might be the case for a hardware vulnerability (e.g. Spectre, Meltdown, etc.). Therefore, we suggest a new product status "under_investigation" which allows a vendor (or any other publishing party) to state for which products a customer can expect to get a definitive / authoritative statement on the product status regarding the current vulnerability.

**Comment by sthagen** [comment]
See comment in PR (otherwise approved :+1: from my side ...
