### ISSUE TITLE
Clarify CPE version 

### ISSUE THREAD

**Issue by sonnyvanlingen** [oasis-tcs/csaf#796]
As can be read in `3.1.3.3.1 Full Product Name Type - Product Identification Helper - CPE`, the text includes a reference to the CPE Naming Specification Version 2.3 for more details.

It is not documented explicitly that CPE version 2.3 is required, although one could deduce this from:

1) the regular expression provided
2) the reference to the CPE 2.3 Naming specification.

For usability reasons. I suggest to clarify in the text which version of CPE is used

**Comment by tschmidtb51** [comment]
Even though we mention only CPE 2.3 as reference both, CPE 2.2 and CPE 2.3, are allowed.

**Comment by sonnyvanlingen** [comment]
Right, indeed the regular expression seems to allow both.
My suggestion still stands, let's clarify textually :)

**Comment by tschmidtb51** [comment]
I added a suggestion to resolve it with #800

**Comment by sonnyvanlingen** [comment]
LGTM
