### ISSUE TITLE
Add `$schema` to `testcases_json_schema.json`

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#824]
Currently, we are missing the `$schema` in `testcases_json_schema.json` which results in errors as we specify it in `testcases.json`.

**Comment by milux** [comment]
Isn't it supposed to be exactly the other way around?
Isn't the schema violated by adding `$schema` to your JSON payload, as this doesn't seem to be specified?

**Comment by tschmidtb51** [comment]
I agree that my wording was bad: True is that `$schema` is not defined in `testcases_json_schema.json` and therefore its usage in `testcases.json` results in an error.
