### ISSUE TITLE
CVSS information is not in the FIRST recommended data representation format

### ISSUE THREAD

**Issue by chandanbn** [oasis-tcs/csaf#9]
Looks like the CVSS information is not encoded using the recommended JSON format:
https://github.com/oasis-tcs/csaf/blob/2803752b3012bd7ad49f68acbc6cce0f78833835/sandbox/csaf_2.0/json_schema/csaf_json_schema.json#L440

CVSS SIG has a recommended JSON schema for storing and exchanging CVSS scores:
https://www.first.org/cvss/data-representations

There are few issues with CVSS in current csaf_json_schema.json:
1) CVSS scores are strings instead of a number. Which means consumers may have to convert a string to number to for proper processing. JSON allows numbers, so doesn't make sense to store a number as a string.
2) if CVSS version number is part of the field name (for eg., "base_score_**v3**") when there is a CVSS 3.1 or 4.0, you may have to change the schema (and CSAF version). The FIRST CVSS json schema encodes it in a "version" field. This allows better abstractions, and backwards/forwards compatibility.
3) No validation on format of the vector string format. The FIRST CVSS json schema does have validation builtin.

Suggested fix: make cvss_score_sets an array of objects that $ref to FIRST cvss json schema.

**Comment by santosomar** [comment]
Shared this issue with the TC at the following thread: https://lists.oasis-open.org/archives/csaf/201905/msg00002.html 

This also gives us flexibility to change the CVSS version (once a new version of CVSS is released) and not be stuck with _score_set_v3, base_score_v3, temporal_score_v3, environmental_score_v3_, etc.

**Comment by santosomar** [comment]
For completeness, I am including the direct link to the CVSS 3.0 JSON schema: https://www.first.org/cvss/cvss-v3.0.json

**Comment by santosomar** [comment]
The TC decided to only convert the existing CVRF 1.2 elements into JSON and the
current format supports the CVSS vector, which can then be translated and
decomposed into FIRST format.

Also documented in the Common Security Advisory Framework (CSAF) TC Monthly Meeting Minutes
Meeting Date: May 29, 2019

**Comment by santosomar** [comment]
Addressed in https://github.com/oasis-tcs/csaf/pull/21

**Comment by santosomar** [comment]
CVSS Scores are now represented as such:
```
 "scores": {
            "type": "array",
            "items": {
              "product_ids": "#/definitions/products_t",
              "cvss_v20": {
                "$ref": "https://www.first.org/cvss/cvss-v2.0.json"
              },
              "cvss_v30": {
                "$ref": "https://www.first.org/cvss/cvss-v3.0.json"
              },
              "cvss_v31": {
                "$ref": "https://www.first.org/cvss/cvss-v3.1.json"
              }
            }
```
This was done via Pull Request: https://github.com/oasis-tcs/csaf/pull/21 by Eric Johnson.
