### ISSUE TITLE
Fix multiple full_product_names in relationship

### ISSUE THREAD

**Issue by tolim** [oasis-tcs/csaf#98]
It is not conclusive to me why we allow multiple `full_product_names` in `product_tree/relationships`. One `relationship` element links two products and may produce one new product name and identifier in `full_product_name`. In this context it does not make sense to allow multiple `full_product_names`.

Btw, this is explicitly allowed by CVRF 1.2:

> The prod:Relationship element MUST be present with cardinality [0, ∞] in prod:Tree and if given MUST contain one or more prod:FullProductName instances. » [CSAF-5.1.3-1]

At the moment we do not require the property `full_product_name` within `product_tree/relationships`. This does not conform to CVRF 1.2, but I propose not to change this.

**Comment by sthagen** [comment]
As stated in my review of the pull request I can easily imagine many components together constructing the insecure situation the advisory tries to mitgate: An nginx server running in a docker container with a specific hypervisor on a specific operating system when ipv6 is active and the application server is a so-and-so in a such-and-such configuration ...

**Comment by santosomar** [comment]
This was addressed in pull request #99
